#include "mongo.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <limits.h>
#include <time.h>
#include <syslog.h>
#include <uuid.h>
#include <locale.h>
#include <ctype.h>
#include <iconv.h>

int gn;

int
is_common(char *v) {

if (strlen(v)==1) return(1);

if (strcmp("update",v)==0) return(1);
if (strcmp("a",v)==0) return(1);
if (strcmp("ability",v)==0) return(1);
if (strcmp("able",v)==0) return(1);
if (strcmp("about",v)==0) return(1);
if (strcmp("about",v)==0) return(1);
if (strcmp("above",v)==0) return(1);
if (strcmp("above",v)==0) return(1);
if (strcmp("absence",v)==0) return(1);
if (strcmp("absolutely",v)==0) return(1);
if (strcmp("academic",v)==0) return(1);
if (strcmp("accept",v)==0) return(1);
if (strcmp("access",v)==0) return(1);
if (strcmp("accident",v)==0) return(1);
if (strcmp("accompany",v)==0) return(1);
if (strcmp("according to",v)==0) return(1);
if (strcmp("account",v)==0) return(1);
if (strcmp("account",v)==0) return(1);
if (strcmp("achieve",v)==0) return(1);
if (strcmp("achievement",v)==0) return(1);
if (strcmp("acid",v)==0) return(1);
if (strcmp("acquire",v)==0) return(1);
if (strcmp("across",v)==0) return(1);
if (strcmp("act",v)==0) return(1);
if (strcmp("act",v)==0) return(1);
if (strcmp("action",v)==0) return(1);
if (strcmp("active",v)==0) return(1);
if (strcmp("activity",v)==0) return(1);
if (strcmp("actual",v)==0) return(1);
if (strcmp("actually",v)==0) return(1);
if (strcmp("add",v)==0) return(1);
if (strcmp("addition",v)==0) return(1);
if (strcmp("additional",v)==0) return(1);
if (strcmp("address",v)==0) return(1);
if (strcmp("address",v)==0) return(1);
if (strcmp("administration",v)==0) return(1);
if (strcmp("admit",v)==0) return(1);
if (strcmp("adopt",v)==0) return(1);
if (strcmp("adult",v)==0) return(1);
if (strcmp("advance",v)==0) return(1);
if (strcmp("advantage",v)==0) return(1);
if (strcmp("advice",v)==0) return(1);
if (strcmp("advise",v)==0) return(1);
if (strcmp("affair",v)==0) return(1);
if (strcmp("affect",v)==0) return(1);
if (strcmp("afford",v)==0) return(1);
if (strcmp("afraid",v)==0) return(1);
if (strcmp("after",v)==0) return(1);
if (strcmp("after",v)==0) return(1);
if (strcmp("afternoon",v)==0) return(1);
if (strcmp("afterwards",v)==0) return(1);
if (strcmp("again",v)==0) return(1);
if (strcmp("against",v)==0) return(1);
if (strcmp("age",v)==0) return(1);
if (strcmp("agency",v)==0) return(1);
if (strcmp("agent",v)==0) return(1);
if (strcmp("ago",v)==0) return(1);
if (strcmp("agree",v)==0) return(1);
if (strcmp("agreement",v)==0) return(1);
if (strcmp("ahead",v)==0) return(1);
if (strcmp("aid",v)==0) return(1);
if (strcmp("aim",v)==0) return(1);
if (strcmp("aim",v)==0) return(1);
if (strcmp("air",v)==0) return(1);
if (strcmp("aircraft",v)==0) return(1);
if (strcmp("all",v)==0) return(1);
if (strcmp("all",v)==0) return(1);
if (strcmp("allow",v)==0) return(1);
if (strcmp("almost",v)==0) return(1);
if (strcmp("alone",v)==0) return(1);
if (strcmp("alone",v)==0) return(1);
if (strcmp("along",v)==0) return(1);
if (strcmp("along",v)==0) return(1);
if (strcmp("already",v)==0) return(1);
if (strcmp("alright",v)==0) return(1);
if (strcmp("also",v)==0) return(1);
if (strcmp("alternative",v)==0) return(1);
if (strcmp("alternative",v)==0) return(1);
if (strcmp("although",v)==0) return(1);
if (strcmp("always",v)==0) return(1);
if (strcmp("am",v)==0) return(1);
if (strcmp("among",v)==0) return(1);
if (strcmp("amongst",v)==0) return(1);
if (strcmp("amount",v)==0) return(1);
if (strcmp("an",v)==0) return(1);
if (strcmp("analysis",v)==0) return(1);
if (strcmp("ancient",v)==0) return(1);
if (strcmp("and",v)==0) return(1);
if (strcmp("animal",v)==0) return(1);
if (strcmp("announce",v)==0) return(1);
if (strcmp("annual",v)==0) return(1);
if (strcmp("another",v)==0) return(1);
if (strcmp("answer",v)==0) return(1);
if (strcmp("answer",v)==0) return(1);
if (strcmp("any",v)==0) return(1);
if (strcmp("anybody",v)==0) return(1);
if (strcmp("anyone",v)==0) return(1);
if (strcmp("anything",v)==0) return(1);
if (strcmp("anyway",v)==0) return(1);
if (strcmp("apart",v)==0) return(1);
if (strcmp("apparent",v)==0) return(1);
if (strcmp("apparently",v)==0) return(1);
if (strcmp("appeal",v)==0) return(1);
if (strcmp("appeal",v)==0) return(1);
if (strcmp("appear",v)==0) return(1);
if (strcmp("appearance",v)==0) return(1);
if (strcmp("application",v)==0) return(1);
if (strcmp("apply",v)==0) return(1);
if (strcmp("appoint",v)==0) return(1);
if (strcmp("appointment",v)==0) return(1);
if (strcmp("approach",v)==0) return(1);
if (strcmp("approach",v)==0) return(1);
if (strcmp("appropriate",v)==0) return(1);
if (strcmp("approve",v)==0) return(1);
if (strcmp("area",v)==0) return(1);
if (strcmp("argue",v)==0) return(1);
if (strcmp("argument",v)==0) return(1);
if (strcmp("arise",v)==0) return(1);
if (strcmp("arm",v)==0) return(1);
if (strcmp("army",v)==0) return(1);
if (strcmp("around",v)==0) return(1);
if (strcmp("around",v)==0) return(1);
if (strcmp("arrange",v)==0) return(1);
if (strcmp("arrangement",v)==0) return(1);
if (strcmp("arrive",v)==0) return(1);
if (strcmp("art",v)==0) return(1);
if (strcmp("article",v)==0) return(1);
if (strcmp("artist",v)==0) return(1);
if (strcmp("as",v)==0) return(1);
if (strcmp("as",v)==0) return(1);
if (strcmp("as",v)==0) return(1);
if (strcmp("ask",v)==0) return(1);
if (strcmp("aspect",v)==0) return(1);
if (strcmp("assembly",v)==0) return(1);
if (strcmp("assess",v)==0) return(1);
if (strcmp("assessment",v)==0) return(1);
if (strcmp("asset",v)==0) return(1);
if (strcmp("associate",v)==0) return(1);
if (strcmp("association",v)==0) return(1);
if (strcmp("assume",v)==0) return(1);
if (strcmp("assumption",v)==0) return(1);
if (strcmp("at",v)==0) return(1);
if (strcmp("atmosphere",v)==0) return(1);
if (strcmp("attach",v)==0) return(1);
if (strcmp("attack",v)==0) return(1);
if (strcmp("attack",v)==0) return(1);
if (strcmp("attempt",v)==0) return(1);
if (strcmp("attempt",v)==0) return(1);
if (strcmp("attend",v)==0) return(1);
if (strcmp("attention",v)==0) return(1);
if (strcmp("attitude",v)==0) return(1);
if (strcmp("attract",v)==0) return(1);
if (strcmp("attractive",v)==0) return(1);
if (strcmp("audience",v)==0) return(1);
if (strcmp("author",v)==0) return(1);
if (strcmp("authority",v)==0) return(1);
if (strcmp("available",v)==0) return(1);
if (strcmp("average",v)==0) return(1);
if (strcmp("avoid",v)==0) return(1);
if (strcmp("award",v)==0) return(1);
if (strcmp("award",v)==0) return(1);
if (strcmp("aware",v)==0) return(1);
if (strcmp("away",v)==0) return(1);
if (strcmp("aye",v)==0) return(1);
if (strcmp("baby",v)==0) return(1);
if (strcmp("back",v)==0) return(1);
if (strcmp("back",v)==0) return(1);
if (strcmp("background",v)==0) return(1);
if (strcmp("bad",v)==0) return(1);
if (strcmp("bag",v)==0) return(1);
if (strcmp("balance",v)==0) return(1);
if (strcmp("ball",v)==0) return(1);
if (strcmp("band",v)==0) return(1);
if (strcmp("bank",v)==0) return(1);
if (strcmp("bar",v)==0) return(1);
if (strcmp("base",v)==0) return(1);
if (strcmp("base",v)==0) return(1);
if (strcmp("basic",v)==0) return(1);
if (strcmp("basis",v)==0) return(1);
if (strcmp("battle",v)==0) return(1);
if (strcmp("be",v)==0) return(1);
if (strcmp("bear",v)==0) return(1);
if (strcmp("beat",v)==0) return(1);
if (strcmp("beautiful",v)==0) return(1);
if (strcmp("because",v)==0) return(1);
if (strcmp("become",v)==0) return(1);
if (strcmp("bed",v)==0) return(1);
if (strcmp("bedroom",v)==0) return(1);
if (strcmp("before",v)==0) return(1);
if (strcmp("before",v)==0) return(1);
if (strcmp("before",v)==0) return(1);
if (strcmp("begin",v)==0) return(1);
if (strcmp("beginning",v)==0) return(1);
if (strcmp("behaviour",v)==0) return(1);
if (strcmp("behind",v)==0) return(1);
if (strcmp("belief",v)==0) return(1);
if (strcmp("believe",v)==0) return(1);
if (strcmp("belong",v)==0) return(1);
if (strcmp("below",v)==0) return(1);
if (strcmp("below",v)==0) return(1);
if (strcmp("beneath",v)==0) return(1);
if (strcmp("benefit",v)==0) return(1);
if (strcmp("beside",v)==0) return(1);
if (strcmp("best",v)==0) return(1);
if (strcmp("better",v)==0) return(1);
if (strcmp("between",v)==0) return(1);
if (strcmp("beyond",v)==0) return(1);
if (strcmp("big",v)==0) return(1);
if (strcmp("bill",v)==0) return(1);
if (strcmp("bind",v)==0) return(1);
if (strcmp("bird",v)==0) return(1);
if (strcmp("birth",v)==0) return(1);
if (strcmp("bit",v)==0) return(1);
if (strcmp("black",v)==0) return(1);
if (strcmp("block",v)==0) return(1);
if (strcmp("blood",v)==0) return(1);
if (strcmp("bloody",v)==0) return(1);
if (strcmp("blow",v)==0) return(1);
if (strcmp("blue",v)==0) return(1);
if (strcmp("board",v)==0) return(1);
if (strcmp("boat",v)==0) return(1);
if (strcmp("body",v)==0) return(1);
if (strcmp("bone",v)==0) return(1);
if (strcmp("book",v)==0) return(1);
if (strcmp("border",v)==0) return(1);
if (strcmp("both",v)==0) return(1);
if (strcmp("both",v)==0) return(1);
if (strcmp("bottle",v)==0) return(1);
if (strcmp("bottom",v)==0) return(1);
if (strcmp("box",v)==0) return(1);
if (strcmp("boy",v)==0) return(1);
if (strcmp("brain",v)==0) return(1);
if (strcmp("branch",v)==0) return(1);
if (strcmp("break",v)==0) return(1);
if (strcmp("breath",v)==0) return(1);
if (strcmp("bridge",v)==0) return(1);
if (strcmp("brief",v)==0) return(1);
if (strcmp("bright",v)==0) return(1);
if (strcmp("bring",v)==0) return(1);
if (strcmp("broad",v)==0) return(1);
if (strcmp("brother",v)==0) return(1);
if (strcmp("budget",v)==0) return(1);
if (strcmp("build",v)==0) return(1);
if (strcmp("building",v)==0) return(1);
if (strcmp("burn",v)==0) return(1);
if (strcmp("bus",v)==0) return(1);
if (strcmp("business",v)==0) return(1);
if (strcmp("busy",v)==0) return(1);
if (strcmp("but",v)==0) return(1);
if (strcmp("buy",v)==0) return(1);
if (strcmp("by",v)==0) return(1);
if (strcmp("cabinet",v)==0) return(1);
if (strcmp("call",v)==0) return(1);
if (strcmp("call",v)==0) return(1);
if (strcmp("campaign",v)==0) return(1);
if (strcmp("can",v)==0) return(1);
if (strcmp("candidate",v)==0) return(1);
if (strcmp("capable",v)==0) return(1);
if (strcmp("capacity",v)==0) return(1);
if (strcmp("capital",v)==0) return(1);
if (strcmp("car",v)==0) return(1);
if (strcmp("card",v)==0) return(1);
if (strcmp("care",v)==0) return(1);
if (strcmp("care",v)==0) return(1);
if (strcmp("career",v)==0) return(1);
if (strcmp("careful",v)==0) return(1);
if (strcmp("carefully",v)==0) return(1);
if (strcmp("carry",v)==0) return(1);
if (strcmp("case",v)==0) return(1);
if (strcmp("cash",v)==0) return(1);
if (strcmp("cat",v)==0) return(1);
if (strcmp("catch",v)==0) return(1);
if (strcmp("category",v)==0) return(1);
if (strcmp("cause",v)==0) return(1);
if (strcmp("cause",v)==0) return(1);
if (strcmp("cell",v)==0) return(1);
if (strcmp("central",v)==0) return(1);
if (strcmp("centre",v)==0) return(1);
if (strcmp("century",v)==0) return(1);
if (strcmp("certain",v)==0) return(1);
if (strcmp("certainly",v)==0) return(1);
if (strcmp("chain",v)==0) return(1);
if (strcmp("chair",v)==0) return(1);
if (strcmp("chairman",v)==0) return(1);
if (strcmp("challenge",v)==0) return(1);
if (strcmp("chance",v)==0) return(1);
if (strcmp("change",v)==0) return(1);
if (strcmp("change",v)==0) return(1);
if (strcmp("channel",v)==0) return(1);
if (strcmp("chapter",v)==0) return(1);
if (strcmp("character",v)==0) return(1);
if (strcmp("characteristic",v)==0) return(1);
if (strcmp("charge",v)==0) return(1);
if (strcmp("charge",v)==0) return(1);
if (strcmp("cheap",v)==0) return(1);
if (strcmp("check",v)==0) return(1);
if (strcmp("chemical",v)==0) return(1);
if (strcmp("chief",v)==0) return(1);
if (strcmp("child",v)==0) return(1);
if (strcmp("choice",v)==0) return(1);
if (strcmp("choose",v)==0) return(1);
if (strcmp("church",v)==0) return(1);
if (strcmp("circle",v)==0) return(1);
if (strcmp("circumstance",v)==0) return(1);
if (strcmp("citizen",v)==0) return(1);
if (strcmp("city",v)==0) return(1);
if (strcmp("civil",v)==0) return(1);
if (strcmp("claim",v)==0) return(1);
if (strcmp("claim",v)==0) return(1);
if (strcmp("class",v)==0) return(1);
if (strcmp("clean",v)==0) return(1);
if (strcmp("clear",v)==0) return(1);
if (strcmp("clear",v)==0) return(1);
if (strcmp("clearly",v)==0) return(1);
if (strcmp("client",v)==0) return(1);
if (strcmp("climb",v)==0) return(1);
if (strcmp("close",v)==0) return(1);
if (strcmp("close",v)==0) return(1);
if (strcmp("close",v)==0) return(1);
if (strcmp("closely",v)==0) return(1);
if (strcmp("clothes",v)==0) return(1);
if (strcmp("club",v)==0) return(1);
if (strcmp("coal",v)==0) return(1);
if (strcmp("code",v)==0) return(1);
if (strcmp("coffee",v)==0) return(1);
if (strcmp("cold",v)==0) return(1);
if (strcmp("colleague",v)==0) return(1);
if (strcmp("collect",v)==0) return(1);
if (strcmp("collection",v)==0) return(1);
if (strcmp("college",v)==0) return(1);
if (strcmp("colour",v)==0) return(1);
if (strcmp("combination",v)==0) return(1);
if (strcmp("combine",v)==0) return(1);
if (strcmp("come",v)==0) return(1);
if (strcmp("comment",v)==0) return(1);
if (strcmp("comment",v)==0) return(1);
if (strcmp("commercial",v)==0) return(1);
if (strcmp("commission",v)==0) return(1);
if (strcmp("commit",v)==0) return(1);
if (strcmp("commitment",v)==0) return(1);
if (strcmp("committee",v)==0) return(1);
if (strcmp("common",v)==0) return(1);
if (strcmp("communication",v)==0) return(1);
if (strcmp("community",v)==0) return(1);
if (strcmp("company",v)==0) return(1);
if (strcmp("compare",v)==0) return(1);
if (strcmp("comparison",v)==0) return(1);
if (strcmp("competition",v)==0) return(1);
if (strcmp("complete",v)==0) return(1);
if (strcmp("complete",v)==0) return(1);
if (strcmp("completely",v)==0) return(1);
if (strcmp("complex",v)==0) return(1);
if (strcmp("component",v)==0) return(1);
if (strcmp("computer",v)==0) return(1);
if (strcmp("concentrate",v)==0) return(1);
if (strcmp("concentration",v)==0) return(1);
if (strcmp("concept",v)==0) return(1);
if (strcmp("concern",v)==0) return(1);
if (strcmp("concern",v)==0) return(1);
if (strcmp("concerned",v)==0) return(1);
if (strcmp("conclude",v)==0) return(1);
if (strcmp("conclusion",v)==0) return(1);
if (strcmp("condition",v)==0) return(1);
if (strcmp("conduct",v)==0) return(1);
if (strcmp("conference",v)==0) return(1);
if (strcmp("confidence",v)==0) return(1);
if (strcmp("confirm",v)==0) return(1);
if (strcmp("conflict",v)==0) return(1);
if (strcmp("congress",v)==0) return(1);
if (strcmp("connect",v)==0) return(1);
if (strcmp("connection",v)==0) return(1);
if (strcmp("consequence",v)==0) return(1);
if (strcmp("conservative",v)==0) return(1);
if (strcmp("consider",v)==0) return(1);
if (strcmp("considerable",v)==0) return(1);
if (strcmp("consideration",v)==0) return(1);
if (strcmp("consist",v)==0) return(1);
if (strcmp("constant",v)==0) return(1);
if (strcmp("construction",v)==0) return(1);
if (strcmp("consumer",v)==0) return(1);
if (strcmp("contact",v)==0) return(1);
if (strcmp("contact",v)==0) return(1);
if (strcmp("contain",v)==0) return(1);
if (strcmp("content",v)==0) return(1);
if (strcmp("context",v)==0) return(1);
if (strcmp("continue",v)==0) return(1);
if (strcmp("contract",v)==0) return(1);
if (strcmp("contrast",v)==0) return(1);
if (strcmp("contribute",v)==0) return(1);
if (strcmp("contribution",v)==0) return(1);
if (strcmp("control",v)==0) return(1);
if (strcmp("control",v)==0) return(1);
if (strcmp("convention",v)==0) return(1);
if (strcmp("conversation",v)==0) return(1);
if (strcmp("copy",v)==0) return(1);
if (strcmp("corner",v)==0) return(1);
if (strcmp("corporate",v)==0) return(1);
if (strcmp("correct",v)==0) return(1);
if (strcmp("cos",v)==0) return(1);
if (strcmp("cost",v)==0) return(1);
if (strcmp("cost",v)==0) return(1);
if (strcmp("could",v)==0) return(1);
if (strcmp("council",v)==0) return(1);
if (strcmp("count",v)==0) return(1);
if (strcmp("country",v)==0) return(1);
if (strcmp("county",v)==0) return(1);
if (strcmp("couple",v)==0) return(1);
if (strcmp("course",v)==0) return(1);
if (strcmp("court",v)==0) return(1);
if (strcmp("cover",v)==0) return(1);
if (strcmp("cover",v)==0) return(1);
if (strcmp("create",v)==0) return(1);
if (strcmp("creation",v)==0) return(1);
if (strcmp("credit",v)==0) return(1);
if (strcmp("crime",v)==0) return(1);
if (strcmp("criminal",v)==0) return(1);
if (strcmp("crisis",v)==0) return(1);
if (strcmp("criterion",v)==0) return(1);
if (strcmp("critical",v)==0) return(1);
if (strcmp("criticism",v)==0) return(1);
if (strcmp("cross",v)==0) return(1);
if (strcmp("crowd",v)==0) return(1);
if (strcmp("cry",v)==0) return(1);
if (strcmp("cultural",v)==0) return(1);
if (strcmp("culture",v)==0) return(1);
if (strcmp("cup",v)==0) return(1);
if (strcmp("current",v)==0) return(1);
if (strcmp("currently",v)==0) return(1);
if (strcmp("curriculum",v)==0) return(1);
if (strcmp("customer",v)==0) return(1);
if (strcmp("cut",v)==0) return(1);
if (strcmp("cut",v)==0) return(1);
if (strcmp("damage",v)==0) return(1);
if (strcmp("damage",v)==0) return(1);
if (strcmp("danger",v)==0) return(1);
if (strcmp("dangerous",v)==0) return(1);
if (strcmp("dark",v)==0) return(1);
if (strcmp("data",v)==0) return(1);
if (strcmp("date",v)==0) return(1);
if (strcmp("date",v)==0) return(1);
if (strcmp("daughter",v)==0) return(1);
if (strcmp("day",v)==0) return(1);
if (strcmp("dead",v)==0) return(1);
if (strcmp("deal",v)==0) return(1);
if (strcmp("deal",v)==0) return(1);
if (strcmp("death",v)==0) return(1);
if (strcmp("debate",v)==0) return(1);
if (strcmp("debt",v)==0) return(1);
if (strcmp("decade",v)==0) return(1);
if (strcmp("decide",v)==0) return(1);
if (strcmp("decision",v)==0) return(1);
if (strcmp("declare",v)==0) return(1);
if (strcmp("deep",v)==0) return(1);
if (strcmp("deep",v)==0) return(1);
if (strcmp("defence",v)==0) return(1);
if (strcmp("defendant",v)==0) return(1);
if (strcmp("define",v)==0) return(1);
if (strcmp("definition",v)==0) return(1);
if (strcmp("degree",v)==0) return(1);
if (strcmp("deliver",v)==0) return(1);
if (strcmp("demand",v)==0) return(1);
if (strcmp("demand",v)==0) return(1);
if (strcmp("democratic",v)==0) return(1);
if (strcmp("demonstrate",v)==0) return(1);
if (strcmp("deny",v)==0) return(1);
if (strcmp("department",v)==0) return(1);
if (strcmp("depend",v)==0) return(1);
if (strcmp("deputy",v)==0) return(1);
if (strcmp("derive",v)==0) return(1);
if (strcmp("describe",v)==0) return(1);
if (strcmp("description",v)==0) return(1);
if (strcmp("design",v)==0) return(1);
if (strcmp("design",v)==0) return(1);
if (strcmp("desire",v)==0) return(1);
if (strcmp("desk",v)==0) return(1);
if (strcmp("despite",v)==0) return(1);
if (strcmp("destroy",v)==0) return(1);
if (strcmp("detail",v)==0) return(1);
if (strcmp("detailed",v)==0) return(1);
if (strcmp("determine",v)==0) return(1);
if (strcmp("develop",v)==0) return(1);
if (strcmp("development",v)==0) return(1);
if (strcmp("device",v)==0) return(1);
if (strcmp("did",v)==0) return(1);
if (strcmp("didn",v)==0) return(1);
if (strcmp("die",v)==0) return(1);
if (strcmp("difference",v)==0) return(1);
if (strcmp("different",v)==0) return(1);
if (strcmp("difficult",v)==0) return(1);
if (strcmp("difficulty",v)==0) return(1);
if (strcmp("dinner",v)==0) return(1);
if (strcmp("direct",v)==0) return(1);
if (strcmp("direct",v)==0) return(1);
if (strcmp("direction",v)==0) return(1);
if (strcmp("directly",v)==0) return(1);
if (strcmp("director",v)==0) return(1);
if (strcmp("disappear",v)==0) return(1);
if (strcmp("discipline",v)==0) return(1);
if (strcmp("discover",v)==0) return(1);
if (strcmp("discuss",v)==0) return(1);
if (strcmp("discussion",v)==0) return(1);
if (strcmp("disease",v)==0) return(1);
if (strcmp("display",v)==0) return(1);
if (strcmp("display",v)==0) return(1);
if (strcmp("distance",v)==0) return(1);
if (strcmp("distinction",v)==0) return(1);
if (strcmp("distribution",v)==0) return(1);
if (strcmp("district",v)==0) return(1);
if (strcmp("divide",v)==0) return(1);
if (strcmp("division",v)==0) return(1);
if (strcmp("do",v)==0) return(1);
if (strcmp("doctor",v)==0) return(1);
if (strcmp("document",v)==0) return(1);
if (strcmp("dog",v)==0) return(1);
if (strcmp("domestic",v)==0) return(1);
if (strcmp("door",v)==0) return(1);
if (strcmp("double",v)==0) return(1);
if (strcmp("doubt",v)==0) return(1);
if (strcmp("down",v)==0) return(1);
if (strcmp("down",v)==0) return(1);
if (strcmp("draw",v)==0) return(1);
if (strcmp("drawing",v)==0) return(1);
if (strcmp("dream",v)==0) return(1);
if (strcmp("dress",v)==0) return(1);
if (strcmp("dress",v)==0) return(1);
if (strcmp("drink",v)==0) return(1);
if (strcmp("drink",v)==0) return(1);
if (strcmp("drive",v)==0) return(1);
if (strcmp("drive",v)==0) return(1);
if (strcmp("driver",v)==0) return(1);
if (strcmp("drop",v)==0) return(1);
if (strcmp("drug",v)==0) return(1);
if (strcmp("dry",v)==0) return(1);
if (strcmp("due",v)==0) return(1);
if (strcmp("during",v)==0) return(1);
if (strcmp("duty",v)==0) return(1);
if (strcmp("each",v)==0) return(1);
if (strcmp("ear",v)==0) return(1);
if (strcmp("early",v)==0) return(1);
if (strcmp("early",v)==0) return(1);
if (strcmp("earn",v)==0) return(1);
if (strcmp("earth",v)==0) return(1);
if (strcmp("easily",v)==0) return(1);
if (strcmp("east",v)==0) return(1);
if (strcmp("easy",v)==0) return(1);
if (strcmp("eat",v)==0) return(1);
if (strcmp("economic",v)==0) return(1);
if (strcmp("economy",v)==0) return(1);
if (strcmp("edge",v)==0) return(1);
if (strcmp("editor",v)==0) return(1);
if (strcmp("education",v)==0) return(1);
if (strcmp("educational",v)==0) return(1);
if (strcmp("effect",v)==0) return(1);
if (strcmp("effective",v)==0) return(1);
if (strcmp("effectively",v)==0) return(1);
if (strcmp("effort",v)==0) return(1);
if (strcmp("egg",v)==0) return(1);
if (strcmp("either",v)==0) return(1);
if (strcmp("either",v)==0) return(1);
if (strcmp("elderly",v)==0) return(1);
if (strcmp("election",v)==0) return(1);
if (strcmp("element",v)==0) return(1);
if (strcmp("else",v)==0) return(1);
if (strcmp("elsewhere",v)==0) return(1);
if (strcmp("emerge",v)==0) return(1);
if (strcmp("emphasis",v)==0) return(1);
if (strcmp("employ",v)==0) return(1);
if (strcmp("employee",v)==0) return(1);
if (strcmp("employer",v)==0) return(1);
if (strcmp("employment",v)==0) return(1);
if (strcmp("empty",v)==0) return(1);
if (strcmp("enable",v)==0) return(1);
if (strcmp("encourage",v)==0) return(1);
if (strcmp("end",v)==0) return(1);
if (strcmp("end",v)==0) return(1);
if (strcmp("enemy",v)==0) return(1);
if (strcmp("energy",v)==0) return(1);
if (strcmp("engine",v)==0) return(1);
if (strcmp("engineering",v)==0) return(1);
if (strcmp("enjoy",v)==0) return(1);
if (strcmp("enough",v)==0) return(1);
if (strcmp("enough",v)==0) return(1);
if (strcmp("ensure",v)==0) return(1);
if (strcmp("enter",v)==0) return(1);
if (strcmp("enterprise",v)==0) return(1);
if (strcmp("entire",v)==0) return(1);
if (strcmp("entirely",v)==0) return(1);
if (strcmp("entitle",v)==0) return(1);
if (strcmp("entry",v)==0) return(1);
if (strcmp("environment",v)==0) return(1);
if (strcmp("environmental",v)==0) return(1);
if (strcmp("equal",v)==0) return(1);
if (strcmp("equally",v)==0) return(1);
if (strcmp("equipment",v)==0) return(1);
if (strcmp("error",v)==0) return(1);
if (strcmp("escape",v)==0) return(1);
if (strcmp("especially",v)==0) return(1);
if (strcmp("essential",v)==0) return(1);
if (strcmp("establish",v)==0) return(1);
if (strcmp("establishment",v)==0) return(1);
if (strcmp("estate",v)==0) return(1);
if (strcmp("estimate",v)==0) return(1);
if (strcmp("even",v)==0) return(1);
if (strcmp("evening",v)==0) return(1);
if (strcmp("event",v)==0) return(1);
if (strcmp("eventually",v)==0) return(1);
if (strcmp("ever",v)==0) return(1);
if (strcmp("every",v)==0) return(1);
if (strcmp("everybody",v)==0) return(1);
if (strcmp("everyone",v)==0) return(1);
if (strcmp("everything",v)==0) return(1);
if (strcmp("evidence",v)==0) return(1);
if (strcmp("exactly",v)==0) return(1);
if (strcmp("examination",v)==0) return(1);
if (strcmp("examine",v)==0) return(1);
if (strcmp("example",v)==0) return(1);
if (strcmp("excellent",v)==0) return(1);
if (strcmp("except",v)==0) return(1);
if (strcmp("exchange",v)==0) return(1);
if (strcmp("executive",v)==0) return(1);
if (strcmp("exercise",v)==0) return(1);
if (strcmp("exercise",v)==0) return(1);
if (strcmp("exhibition",v)==0) return(1);
if (strcmp("exist",v)==0) return(1);
if (strcmp("existence",v)==0) return(1);
if (strcmp("existing",v)==0) return(1);
if (strcmp("expect",v)==0) return(1);
if (strcmp("expectation",v)==0) return(1);
if (strcmp("expenditure",v)==0) return(1);
if (strcmp("expense",v)==0) return(1);
if (strcmp("expensive",v)==0) return(1);
if (strcmp("experience",v)==0) return(1);
if (strcmp("experience",v)==0) return(1);
if (strcmp("experiment",v)==0) return(1);
if (strcmp("expert",v)==0) return(1);
if (strcmp("explain",v)==0) return(1);
if (strcmp("explanation",v)==0) return(1);
if (strcmp("explore",v)==0) return(1);
if (strcmp("express",v)==0) return(1);
if (strcmp("expression",v)==0) return(1);
if (strcmp("extend",v)==0) return(1);
if (strcmp("extent",v)==0) return(1);
if (strcmp("external",v)==0) return(1);
if (strcmp("extra",v)==0) return(1);
if (strcmp("extremely",v)==0) return(1);
if (strcmp("eye",v)==0) return(1);
if (strcmp("face",v)==0) return(1);
if (strcmp("face",v)==0) return(1);
if (strcmp("facility",v)==0) return(1);
if (strcmp("fact",v)==0) return(1);
if (strcmp("factor",v)==0) return(1);
if (strcmp("factory",v)==0) return(1);
if (strcmp("fail",v)==0) return(1);
if (strcmp("failure",v)==0) return(1);
if (strcmp("fair",v)==0) return(1);
if (strcmp("fairly",v)==0) return(1);
if (strcmp("faith",v)==0) return(1);
if (strcmp("fall",v)==0) return(1);
if (strcmp("fall",v)==0) return(1);
if (strcmp("familiar",v)==0) return(1);
if (strcmp("family",v)==0) return(1);
if (strcmp("famous",v)==0) return(1);
if (strcmp("far",v)==0) return(1);
if (strcmp("far",v)==0) return(1);
if (strcmp("farm",v)==0) return(1);
if (strcmp("farmer",v)==0) return(1);
if (strcmp("fashion",v)==0) return(1);
if (strcmp("fast",v)==0) return(1);
if (strcmp("fast",v)==0) return(1);
if (strcmp("father",v)==0) return(1);
if (strcmp("favour",v)==0) return(1);
if (strcmp("fear",v)==0) return(1);
if (strcmp("fear",v)==0) return(1);
if (strcmp("feature",v)==0) return(1);
if (strcmp("fee",v)==0) return(1);
if (strcmp("feel",v)==0) return(1);
if (strcmp("feeling",v)==0) return(1);
if (strcmp("female",v)==0) return(1);
if (strcmp("few",v)==0) return(1);
if (strcmp("few",v)==0) return(1);
if (strcmp("field",v)==0) return(1);
if (strcmp("fight",v)==0) return(1);
if (strcmp("figure",v)==0) return(1);
if (strcmp("file",v)==0) return(1);
if (strcmp("fill",v)==0) return(1);
if (strcmp("film",v)==0) return(1);
if (strcmp("final",v)==0) return(1);
if (strcmp("finally",v)==0) return(1);
if (strcmp("finance",v)==0) return(1);
if (strcmp("financial",v)==0) return(1);
if (strcmp("find",v)==0) return(1);
if (strcmp("finding",v)==0) return(1);
if (strcmp("fine",v)==0) return(1);
if (strcmp("finger",v)==0) return(1);
if (strcmp("finish",v)==0) return(1);
if (strcmp("fire",v)==0) return(1);
if (strcmp("firm",v)==0) return(1);
if (strcmp("first",v)==0) return(1);
if (strcmp("fish",v)==0) return(1);
if (strcmp("fit",v)==0) return(1);
if (strcmp("fix",v)==0) return(1);
if (strcmp("flat",v)==0) return(1);
if (strcmp("flight",v)==0) return(1);
if (strcmp("floor",v)==0) return(1);
if (strcmp("flow",v)==0) return(1);
if (strcmp("flower",v)==0) return(1);
if (strcmp("fly",v)==0) return(1);
if (strcmp("focus",v)==0) return(1);
if (strcmp("follow",v)==0) return(1);
if (strcmp("following",v)==0) return(1);
if (strcmp("food",v)==0) return(1);
if (strcmp("foot",v)==0) return(1);
if (strcmp("football",v)==0) return(1);
if (strcmp("for",v)==0) return(1);
if (strcmp("for",v)==0) return(1);
if (strcmp("force",v)==0) return(1);
if (strcmp("force",v)==0) return(1);
if (strcmp("foreign",v)==0) return(1);
if (strcmp("forest",v)==0) return(1);
if (strcmp("forget",v)==0) return(1);
if (strcmp("form",v)==0) return(1);
if (strcmp("form",v)==0) return(1);
if (strcmp("formal",v)==0) return(1);
if (strcmp("former",v)==0) return(1);
if (strcmp("forward",v)==0) return(1);
if (strcmp("foundation",v)==0) return(1);
if (strcmp("free",v)==0) return(1);
if (strcmp("freedom",v)==0) return(1);
if (strcmp("frequently",v)==0) return(1);
if (strcmp("fresh",v)==0) return(1);
if (strcmp("friend",v)==0) return(1);
if (strcmp("from",v)==0) return(1);
if (strcmp("front",v)==0) return(1);
if (strcmp("front",v)==0) return(1);
if (strcmp("fruit",v)==0) return(1);
if (strcmp("fuel",v)==0) return(1);
if (strcmp("full",v)==0) return(1);
if (strcmp("fully",v)==0) return(1);
if (strcmp("function",v)==0) return(1);
if (strcmp("fund",v)==0) return(1);
if (strcmp("funny",v)==0) return(1);
if (strcmp("further",v)==0) return(1);
if (strcmp("future",v)==0) return(1);
if (strcmp("future",v)==0) return(1);
if (strcmp("gain",v)==0) return(1);
if (strcmp("game",v)==0) return(1);
if (strcmp("garden",v)==0) return(1);
if (strcmp("gas",v)==0) return(1);
if (strcmp("gate",v)==0) return(1);
if (strcmp("gather",v)==0) return(1);
if (strcmp("general",v)==0) return(1);
if (strcmp("general",v)==0) return(1);
if (strcmp("generally",v)==0) return(1);
if (strcmp("generate",v)==0) return(1);
if (strcmp("generation",v)==0) return(1);
if (strcmp("gentleman",v)==0) return(1);
if (strcmp("get",v)==0) return(1);
if (strcmp("girl",v)==0) return(1);
if (strcmp("give",v)==0) return(1);
if (strcmp("glass",v)==0) return(1);
if (strcmp("go",v)==0) return(1);
if (strcmp("goal",v)==0) return(1);
if (strcmp("god",v)==0) return(1);
if (strcmp("gold",v)==0) return(1);
if (strcmp("good",v)==0) return(1);
if (strcmp("good",v)==0) return(1);
if (strcmp("government",v)==0) return(1);
if (strcmp("grant",v)==0) return(1);
if (strcmp("grant",v)==0) return(1);
if (strcmp("great",v)==0) return(1);
if (strcmp("green",v)==0) return(1);
if (strcmp("grey",v)==0) return(1);
if (strcmp("ground",v)==0) return(1);
if (strcmp("group",v)==0) return(1);
if (strcmp("grow",v)==0) return(1);
if (strcmp("growing",v)==0) return(1);
if (strcmp("growth",v)==0) return(1);
if (strcmp("guest",v)==0) return(1);
if (strcmp("guide",v)==0) return(1);
if (strcmp("gun",v)==0) return(1);
if (strcmp("hair",v)==0) return(1);
if (strcmp("half",v)==0) return(1);
if (strcmp("half",v)==0) return(1);
if (strcmp("hall",v)==0) return(1);
if (strcmp("hand",v)==0) return(1);
if (strcmp("hand",v)==0) return(1);
if (strcmp("handle",v)==0) return(1);
if (strcmp("hang",v)==0) return(1);
if (strcmp("happen",v)==0) return(1);
if (strcmp("happy",v)==0) return(1);
if (strcmp("hard",v)==0) return(1);
if (strcmp("hard",v)==0) return(1);
if (strcmp("hardly",v)==0) return(1);
if (strcmp("hate",v)==0) return(1);
if (strcmp("have",v)==0) return(1);
if (strcmp("he",v)==0) return(1);
if (strcmp("head",v)==0) return(1);
if (strcmp("head",v)==0) return(1);
if (strcmp("health",v)==0) return(1);
if (strcmp("hear",v)==0) return(1);
if (strcmp("heart",v)==0) return(1);
if (strcmp("heat",v)==0) return(1);
if (strcmp("heavy",v)==0) return(1);
if (strcmp("hell",v)==0) return(1);
if (strcmp("help",v)==0) return(1);
if (strcmp("help",v)==0) return(1);
if (strcmp("hence",v)==0) return(1);
if (strcmp("her",v)==0) return(1);
if (strcmp("her",v)==0) return(1);
if (strcmp("here",v)==0) return(1);
if (strcmp("herself",v)==0) return(1);
if (strcmp("hide",v)==0) return(1);
if (strcmp("high",v)==0) return(1);
if (strcmp("high",v)==0) return(1);
if (strcmp("highly",v)==0) return(1);
if (strcmp("hill",v)==0) return(1);
if (strcmp("him",v)==0) return(1);
if (strcmp("himself",v)==0) return(1);
if (strcmp("his",v)==0) return(1);
if (strcmp("his",v)==0) return(1);
if (strcmp("historical",v)==0) return(1);
if (strcmp("history",v)==0) return(1);
if (strcmp("hit",v)==0) return(1);
if (strcmp("hold",v)==0) return(1);
if (strcmp("hole",v)==0) return(1);
if (strcmp("holiday",v)==0) return(1);
if (strcmp("home",v)==0) return(1);
if (strcmp("home",v)==0) return(1);
if (strcmp("hope",v)==0) return(1);
if (strcmp("hope",v)==0) return(1);
if (strcmp("horse",v)==0) return(1);
if (strcmp("hospital",v)==0) return(1);
if (strcmp("hot",v)==0) return(1);
if (strcmp("hotel",v)==0) return(1);
if (strcmp("hour",v)==0) return(1);
if (strcmp("house",v)==0) return(1);
if (strcmp("household",v)==0) return(1);
if (strcmp("housing",v)==0) return(1);
if (strcmp("how",v)==0) return(1);
if (strcmp("however",v)==0) return(1);
if (strcmp("huge",v)==0) return(1);
if (strcmp("human",v)==0) return(1);
if (strcmp("human",v)==0) return(1);
if (strcmp("hurt",v)==0) return(1);
if (strcmp("husband",v)==0) return(1);
if (strcmp("i",v)==0) return(1);
if (strcmp("idea",v)==0) return(1);
if (strcmp("identify",v)==0) return(1);
if (strcmp("if",v)==0) return(1);
if (strcmp("ignore",v)==0) return(1);
if (strcmp("illustrate",v)==0) return(1);
if (strcmp("image",v)==0) return(1);
if (strcmp("imagine",v)==0) return(1);
if (strcmp("immediate",v)==0) return(1);
if (strcmp("immediately",v)==0) return(1);
if (strcmp("impact",v)==0) return(1);
if (strcmp("implication",v)==0) return(1);
if (strcmp("imply",v)==0) return(1);
if (strcmp("importance",v)==0) return(1);
if (strcmp("important",v)==0) return(1);
if (strcmp("impose",v)==0) return(1);
if (strcmp("impossible",v)==0) return(1);
if (strcmp("impression",v)==0) return(1);
if (strcmp("improve",v)==0) return(1);
if (strcmp("improvement",v)==0) return(1);
if (strcmp("in",v)==0) return(1);
if (strcmp("in",v)==0) return(1);
if (strcmp("incident",v)==0) return(1);
if (strcmp("include",v)==0) return(1);
if (strcmp("including",v)==0) return(1);
if (strcmp("income",v)==0) return(1);
if (strcmp("increase",v)==0) return(1);
if (strcmp("increase",v)==0) return(1);
if (strcmp("increased",v)==0) return(1);
if (strcmp("increasingly",v)==0) return(1);
if (strcmp("indeed",v)==0) return(1);
if (strcmp("independent",v)==0) return(1);
if (strcmp("index",v)==0) return(1);
if (strcmp("indicate",v)==0) return(1);
if (strcmp("individual",v)==0) return(1);
if (strcmp("individual",v)==0) return(1);
if (strcmp("industrial",v)==0) return(1);
if (strcmp("industry",v)==0) return(1);
if (strcmp("influence",v)==0) return(1);
if (strcmp("influence",v)==0) return(1);
if (strcmp("inform",v)==0) return(1);
if (strcmp("information",v)==0) return(1);
if (strcmp("initial",v)==0) return(1);
if (strcmp("initiative",v)==0) return(1);
if (strcmp("injury",v)==0) return(1);
if (strcmp("inside",v)==0) return(1);
if (strcmp("inside",v)==0) return(1);
if (strcmp("insist",v)==0) return(1);
if (strcmp("instance",v)==0) return(1);
if (strcmp("instead",v)==0) return(1);
if (strcmp("institute",v)==0) return(1);
if (strcmp("institution",v)==0) return(1);
if (strcmp("instruction",v)==0) return(1);
if (strcmp("instrument",v)==0) return(1);
if (strcmp("insurance",v)==0) return(1);
if (strcmp("intend",v)==0) return(1);
if (strcmp("intention",v)==0) return(1);
if (strcmp("interest",v)==0) return(1);
if (strcmp("interested",v)==0) return(1);
if (strcmp("interesting",v)==0) return(1);
if (strcmp("internal",v)==0) return(1);
if (strcmp("international",v)==0) return(1);
if (strcmp("interpretation",v)==0) return(1);
if (strcmp("interview",v)==0) return(1);
if (strcmp("into",v)==0) return(1);
if (strcmp("introduce",v)==0) return(1);
if (strcmp("introduction",v)==0) return(1);
if (strcmp("investigate",v)==0) return(1);
if (strcmp("investigation",v)==0) return(1);
if (strcmp("investment",v)==0) return(1);
if (strcmp("invite",v)==0) return(1);
if (strcmp("involve",v)==0) return(1);
if (strcmp("iron",v)==0) return(1);
if (strcmp("island",v)==0) return(1);
if (strcmp("issue",v)==0) return(1);
if (strcmp("issue",v)==0) return(1);
if (strcmp("is",v)==0) return(1);
if (strcmp("isn",v)==0) return(1);
if (strcmp("it",v)==0) return(1);
if (strcmp("item",v)==0) return(1);
if (strcmp("its",v)==0) return(1);
if (strcmp("itself",v)==0) return(1);
if (strcmp("job",v)==0) return(1);
if (strcmp("join",v)==0) return(1);
if (strcmp("joint",v)==0) return(1);
if (strcmp("journey",v)==0) return(1);
if (strcmp("judge",v)==0) return(1);
if (strcmp("judge",v)==0) return(1);
if (strcmp("jump",v)==0) return(1);
if (strcmp("just",v)==0) return(1);
if (strcmp("justice",v)==0) return(1);
if (strcmp("keep",v)==0) return(1);
if (strcmp("key",v)==0) return(1);
if (strcmp("key",v)==0) return(1);
if (strcmp("kid",v)==0) return(1);
if (strcmp("kill",v)==0) return(1);
if (strcmp("kind",v)==0) return(1);
if (strcmp("king",v)==0) return(1);
if (strcmp("kitchen",v)==0) return(1);
if (strcmp("knee",v)==0) return(1);
if (strcmp("know",v)==0) return(1);
if (strcmp("knowledge",v)==0) return(1);
if (strcmp("labour",v)==0) return(1);
if (strcmp("labour",v)==0) return(1);
if (strcmp("lack",v)==0) return(1);
if (strcmp("lady",v)==0) return(1);
if (strcmp("land",v)==0) return(1);
if (strcmp("language",v)==0) return(1);
if (strcmp("large",v)==0) return(1);
if (strcmp("largely",v)==0) return(1);
if (strcmp("last",v)==0) return(1);
if (strcmp("last",v)==0) return(1);
if (strcmp("late",v)==0) return(1);
if (strcmp("late",v)==0) return(1);
if (strcmp("later",v)==0) return(1);
if (strcmp("latter",v)==0) return(1);
if (strcmp("laugh",v)==0) return(1);
if (strcmp("launch",v)==0) return(1);
if (strcmp("law",v)==0) return(1);
if (strcmp("lawyer",v)==0) return(1);
if (strcmp("lay",v)==0) return(1);
if (strcmp("lead",v)==0) return(1);
if (strcmp("lead",v)==0) return(1);
if (strcmp("leader",v)==0) return(1);
if (strcmp("leadership",v)==0) return(1);
if (strcmp("leading",v)==0) return(1);
if (strcmp("leaf",v)==0) return(1);
if (strcmp("league",v)==0) return(1);
if (strcmp("lean",v)==0) return(1);
if (strcmp("learn",v)==0) return(1);
if (strcmp("least",v)==0) return(1);
if (strcmp("leave",v)==0) return(1);
if (strcmp("left",v)==0) return(1);
if (strcmp("leg",v)==0) return(1);
if (strcmp("legal",v)==0) return(1);
if (strcmp("legislation",v)==0) return(1);
if (strcmp("length",v)==0) return(1);
if (strcmp("less",v)==0) return(1);
if (strcmp("less",v)==0) return(1);
if (strcmp("let",v)==0) return(1);
if (strcmp("letter",v)==0) return(1);
if (strcmp("level",v)==0) return(1);
if (strcmp("liability",v)==0) return(1);
if (strcmp("liberal",v)==0) return(1);
if (strcmp("library",v)==0) return(1);
if (strcmp("lie",v)==0) return(1);
if (strcmp("life",v)==0) return(1);
if (strcmp("lift",v)==0) return(1);
if (strcmp("light",v)==0) return(1);
if (strcmp("light",v)==0) return(1);
if (strcmp("like",v)==0) return(1);
if (strcmp("like",v)==0) return(1);
if (strcmp("likely",v)==0) return(1);
if (strcmp("limit",v)==0) return(1);
if (strcmp("limit",v)==0) return(1);
if (strcmp("limited",v)==0) return(1);
if (strcmp("line",v)==0) return(1);
if (strcmp("link",v)==0) return(1);
if (strcmp("link",v)==0) return(1);
if (strcmp("lip",v)==0) return(1);
if (strcmp("list",v)==0) return(1);
if (strcmp("listen",v)==0) return(1);
if (strcmp("literature",v)==0) return(1);
if (strcmp("little",v)==0) return(1);
if (strcmp("little",v)==0) return(1);
if (strcmp("little",v)==0) return(1);
if (strcmp("live",v)==0) return(1);
if (strcmp("living",v)==0) return(1);
if (strcmp("loan",v)==0) return(1);
if (strcmp("local",v)==0) return(1);
if (strcmp("location",v)==0) return(1);
if (strcmp("long",v)==0) return(1);
if (strcmp("long",v)==0) return(1);
if (strcmp("look",v)==0) return(1);
if (strcmp("look",v)==0) return(1);
if (strcmp("lord",v)==0) return(1);
if (strcmp("lose",v)==0) return(1);
if (strcmp("loss",v)==0) return(1);
if (strcmp("lot",v)==0) return(1);
if (strcmp("love",v)==0) return(1);
if (strcmp("love",v)==0) return(1);
if (strcmp("lovely",v)==0) return(1);
if (strcmp("low",v)==0) return(1);
if (strcmp("lunch",v)==0) return(1);
if (strcmp("machine",v)==0) return(1);
if (strcmp("magazine",v)==0) return(1);
if (strcmp("main",v)==0) return(1);
if (strcmp("mainly",v)==0) return(1);
if (strcmp("maintain",v)==0) return(1);
if (strcmp("major",v)==0) return(1);
if (strcmp("majority",v)==0) return(1);
if (strcmp("make",v)==0) return(1);
if (strcmp("male",v)==0) return(1);
if (strcmp("male",v)==0) return(1);
if (strcmp("man",v)==0) return(1);
if (strcmp("manage",v)==0) return(1);
if (strcmp("management",v)==0) return(1);
if (strcmp("manager",v)==0) return(1);
if (strcmp("manner",v)==0) return(1);
if (strcmp("many",v)==0) return(1);
if (strcmp("map",v)==0) return(1);
if (strcmp("mark",v)==0) return(1);
if (strcmp("mark",v)==0) return(1);
if (strcmp("market",v)==0) return(1);
if (strcmp("market",v)==0) return(1);
if (strcmp("marriage",v)==0) return(1);
if (strcmp("married",v)==0) return(1);
if (strcmp("marry",v)==0) return(1);
if (strcmp("mass",v)==0) return(1);
if (strcmp("master",v)==0) return(1);
if (strcmp("match",v)==0) return(1);
if (strcmp("match",v)==0) return(1);
if (strcmp("material",v)==0) return(1);
if (strcmp("matter",v)==0) return(1);
if (strcmp("matter",v)==0) return(1);
if (strcmp("may",v)==0) return(1);
if (strcmp("may",v)==0) return(1);
if (strcmp("maybe",v)==0) return(1);
if (strcmp("me",v)==0) return(1);
if (strcmp("meal",v)==0) return(1);
if (strcmp("mean",v)==0) return(1);
if (strcmp("meaning",v)==0) return(1);
if (strcmp("means",v)==0) return(1);
if (strcmp("meanwhile",v)==0) return(1);
if (strcmp("measure",v)==0) return(1);
if (strcmp("measure",v)==0) return(1);
if (strcmp("mechanism",v)==0) return(1);
if (strcmp("media",v)==0) return(1);
if (strcmp("medical",v)==0) return(1);
if (strcmp("meet",v)==0) return(1);
if (strcmp("meeting",v)==0) return(1);
if (strcmp("member",v)==0) return(1);
if (strcmp("membership",v)==0) return(1);
if (strcmp("memory",v)==0) return(1);
if (strcmp("mental",v)==0) return(1);
if (strcmp("mention",v)==0) return(1);
if (strcmp("merely",v)==0) return(1);
if (strcmp("message",v)==0) return(1);
if (strcmp("metal",v)==0) return(1);
if (strcmp("method",v)==0) return(1);
if (strcmp("middle",v)==0) return(1);
if (strcmp("might",v)==0) return(1);
if (strcmp("mile",v)==0) return(1);
if (strcmp("military",v)==0) return(1);
if (strcmp("milk",v)==0) return(1);
if (strcmp("mind",v)==0) return(1);
if (strcmp("mind",v)==0) return(1);
if (strcmp("mine",v)==0) return(1);
if (strcmp("minister",v)==0) return(1);
if (strcmp("ministry",v)==0) return(1);
if (strcmp("minute",v)==0) return(1);
if (strcmp("miss",v)==0) return(1);
if (strcmp("mistake",v)==0) return(1);
if (strcmp("model",v)==0) return(1);
if (strcmp("modern",v)==0) return(1);
if (strcmp("module",v)==0) return(1);
if (strcmp("moment",v)==0) return(1);
if (strcmp("money",v)==0) return(1);
if (strcmp("month",v)==0) return(1);
if (strcmp("more",v)==0) return(1);
if (strcmp("more",v)==0) return(1);
if (strcmp("morning",v)==0) return(1);
if (strcmp("most",v)==0) return(1);
if (strcmp("most",v)==0) return(1);
if (strcmp("mother",v)==0) return(1);
if (strcmp("motion",v)==0) return(1);
if (strcmp("motor",v)==0) return(1);
if (strcmp("mountain",v)==0) return(1);
if (strcmp("mouth",v)==0) return(1);
if (strcmp("move",v)==0) return(1);
if (strcmp("move",v)==0) return(1);
if (strcmp("movement",v)==0) return(1);
if (strcmp("much",v)==0) return(1);
if (strcmp("much",v)==0) return(1);
if (strcmp("murder",v)==0) return(1);
if (strcmp("museum",v)==0) return(1);
if (strcmp("music",v)==0) return(1);
if (strcmp("must",v)==0) return(1);
if (strcmp("my",v)==0) return(1);
if (strcmp("myself",v)==0) return(1);
if (strcmp("name",v)==0) return(1);
if (strcmp("name",v)==0) return(1);
if (strcmp("narrow",v)==0) return(1);
if (strcmp("nation",v)==0) return(1);
if (strcmp("national",v)==0) return(1);
if (strcmp("natural",v)==0) return(1);
if (strcmp("nature",v)==0) return(1);
if (strcmp("near",v)==0) return(1);
if (strcmp("nearly",v)==0) return(1);
if (strcmp("necessarily",v)==0) return(1);
if (strcmp("necessary",v)==0) return(1);
if (strcmp("neck",v)==0) return(1);
if (strcmp("need",v)==0) return(1);
if (strcmp("need",v)==0) return(1);
if (strcmp("negotiation",v)==0) return(1);
if (strcmp("neighbour",v)==0) return(1);
if (strcmp("neither",v)==0) return(1);
if (strcmp("network",v)==0) return(1);
if (strcmp("never",v)==0) return(1);
if (strcmp("nevertheless",v)==0) return(1);
if (strcmp("new",v)==0) return(1);
if (strcmp("news",v)==0) return(1);
if (strcmp("newspaper",v)==0) return(1);
if (strcmp("next",v)==0) return(1);
if (strcmp("next",v)==0) return(1);
if (strcmp("nice",v)==0) return(1);
if (strcmp("night",v)==0) return(1);
if (strcmp("no",v)==0) return(1);
if (strcmp("no",v)==0) return(1);
if (strcmp("no",v)==0) return(1);
if (strcmp("no-one",v)==0) return(1);
if (strcmp("nobody",v)==0) return(1);
if (strcmp("nod",v)==0) return(1);
if (strcmp("noise",v)==0) return(1);
if (strcmp("none",v)==0) return(1);
if (strcmp("nor",v)==0) return(1);
if (strcmp("normal",v)==0) return(1);
if (strcmp("normally",v)==0) return(1);
if (strcmp("north",v)==0) return(1);
if (strcmp("northern",v)==0) return(1);
if (strcmp("nose",v)==0) return(1);
if (strcmp("not",v)==0) return(1);
if (strcmp("note",v)==0) return(1);
if (strcmp("note",v)==0) return(1);
if (strcmp("nothing",v)==0) return(1);
if (strcmp("notice",v)==0) return(1);
if (strcmp("notice",v)==0) return(1);
if (strcmp("notion",v)==0) return(1);
if (strcmp("now",v)==0) return(1);
if (strcmp("nuclear",v)==0) return(1);
if (strcmp("number",v)==0) return(1);
if (strcmp("nurse",v)==0) return(1);
if (strcmp("object",v)==0) return(1);
if (strcmp("objective",v)==0) return(1);
if (strcmp("observation",v)==0) return(1);
if (strcmp("observe",v)==0) return(1);
if (strcmp("obtain",v)==0) return(1);
if (strcmp("obvious",v)==0) return(1);
if (strcmp("obviously",v)==0) return(1);
if (strcmp("occasion",v)==0) return(1);
if (strcmp("occur",v)==0) return(1);
if (strcmp("odd",v)==0) return(1);
if (strcmp("of",v)==0) return(1);
if (strcmp("off",v)==0) return(1);
if (strcmp("off",v)==0) return(1);
if (strcmp("offence",v)==0) return(1);
if (strcmp("offer",v)==0) return(1);
if (strcmp("offer",v)==0) return(1);
if (strcmp("office",v)==0) return(1);
if (strcmp("officer",v)==0) return(1);
if (strcmp("official",v)==0) return(1);
if (strcmp("official",v)==0) return(1);
if (strcmp("often",v)==0) return(1);
if (strcmp("oil",v)==0) return(1);
if (strcmp("okay",v)==0) return(1);
if (strcmp("old",v)==0) return(1);
if (strcmp("on",v)==0) return(1);
if (strcmp("on",v)==0) return(1);
if (strcmp("once",v)==0) return(1);
if (strcmp("once",v)==0) return(1);
if (strcmp("one",v)==0) return(1);
if (strcmp("only",v)==0) return(1);
if (strcmp("only",v)==0) return(1);
if (strcmp("onto",v)==0) return(1);
if (strcmp("open",v)==0) return(1);
if (strcmp("open",v)==0) return(1);
if (strcmp("operate",v)==0) return(1);
if (strcmp("operation",v)==0) return(1);
if (strcmp("opinion",v)==0) return(1);
if (strcmp("opportunity",v)==0) return(1);
if (strcmp("opposition",v)==0) return(1);
if (strcmp("option",v)==0) return(1);
if (strcmp("or",v)==0) return(1);
if (strcmp("order",v)==0) return(1);
if (strcmp("order",v)==0) return(1);
if (strcmp("ordinary",v)==0) return(1);
if (strcmp("organisation",v)==0) return(1);
if (strcmp("organise",v)==0) return(1);
if (strcmp("organization",v)==0) return(1);
if (strcmp("origin",v)==0) return(1);
if (strcmp("original",v)==0) return(1);
if (strcmp("other",v)==0) return(1);
if (strcmp("other",v)==0) return(1);
if (strcmp("other",v)==0) return(1);
if (strcmp("otherwise",v)==0) return(1);
if (strcmp("ought",v)==0) return(1);
if (strcmp("our",v)==0) return(1);
if (strcmp("ourselves",v)==0) return(1);
if (strcmp("out",v)==0) return(1);
if (strcmp("outcome",v)==0) return(1);
if (strcmp("output",v)==0) return(1);
if (strcmp("outside",v)==0) return(1);
if (strcmp("outside",v)==0) return(1);
if (strcmp("over",v)==0) return(1);
if (strcmp("over",v)==0) return(1);
if (strcmp("overall",v)==0) return(1);
if (strcmp("own",v)==0) return(1);
if (strcmp("own",v)==0) return(1);
if (strcmp("owner",v)==0) return(1);
if (strcmp("package",v)==0) return(1);
if (strcmp("page",v)==0) return(1);
if (strcmp("pain",v)==0) return(1);
if (strcmp("paint",v)==0) return(1);
if (strcmp("painting",v)==0) return(1);
if (strcmp("pair",v)==0) return(1);
if (strcmp("panel",v)==0) return(1);
if (strcmp("paper",v)==0) return(1);
if (strcmp("parent",v)==0) return(1);
if (strcmp("park",v)==0) return(1);
if (strcmp("parliament",v)==0) return(1);
if (strcmp("part",v)==0) return(1);
if (strcmp("particular",v)==0) return(1);
if (strcmp("particularly",v)==0) return(1);
if (strcmp("partly",v)==0) return(1);
if (strcmp("partner",v)==0) return(1);
if (strcmp("party",v)==0) return(1);
if (strcmp("pass",v)==0) return(1);
if (strcmp("passage",v)==0) return(1);
if (strcmp("past",v)==0) return(1);
if (strcmp("past",v)==0) return(1);
if (strcmp("past",v)==0) return(1);
if (strcmp("path",v)==0) return(1);
if (strcmp("patient",v)==0) return(1);
if (strcmp("pattern",v)==0) return(1);
if (strcmp("pay",v)==0) return(1);
if (strcmp("pay",v)==0) return(1);
if (strcmp("payment",v)==0) return(1);
if (strcmp("peace",v)==0) return(1);
if (strcmp("pension",v)==0) return(1);
if (strcmp("people",v)==0) return(1);
if (strcmp("per",v)==0) return(1);
if (strcmp("percent",v)==0) return(1);
if (strcmp("perfect",v)==0) return(1);
if (strcmp("perform",v)==0) return(1);
if (strcmp("performance",v)==0) return(1);
if (strcmp("perhaps",v)==0) return(1);
if (strcmp("period",v)==0) return(1);
if (strcmp("permanent",v)==0) return(1);
if (strcmp("person",v)==0) return(1);
if (strcmp("personal",v)==0) return(1);
if (strcmp("persuade",v)==0) return(1);
if (strcmp("phase",v)==0) return(1);
if (strcmp("phone",v)==0) return(1);
if (strcmp("photograph",v)==0) return(1);
if (strcmp("physical",v)==0) return(1);
if (strcmp("pick",v)==0) return(1);
if (strcmp("picture",v)==0) return(1);
if (strcmp("piece",v)==0) return(1);
if (strcmp("place",v)==0) return(1);
if (strcmp("place",v)==0) return(1);
if (strcmp("plan",v)==0) return(1);
if (strcmp("plan",v)==0) return(1);
if (strcmp("planning",v)==0) return(1);
if (strcmp("plant",v)==0) return(1);
if (strcmp("plastic",v)==0) return(1);
if (strcmp("plate",v)==0) return(1);
if (strcmp("play",v)==0) return(1);
if (strcmp("play",v)==0) return(1);
if (strcmp("player",v)==0) return(1);
if (strcmp("please",v)==0) return(1);
if (strcmp("pleasure",v)==0) return(1);
if (strcmp("plenty",v)==0) return(1);
if (strcmp("plus",v)==0) return(1);
if (strcmp("pocket",v)==0) return(1);
if (strcmp("point",v)==0) return(1);
if (strcmp("point",v)==0) return(1);
if (strcmp("police",v)==0) return(1);
if (strcmp("policy",v)==0) return(1);
if (strcmp("political",v)==0) return(1);
if (strcmp("politics",v)==0) return(1);
if (strcmp("pool",v)==0) return(1);
if (strcmp("poor",v)==0) return(1);
if (strcmp("popular",v)==0) return(1);
if (strcmp("population",v)==0) return(1);
if (strcmp("position",v)==0) return(1);
if (strcmp("positive",v)==0) return(1);
if (strcmp("possibility",v)==0) return(1);
if (strcmp("possible",v)==0) return(1);
if (strcmp("possibly",v)==0) return(1);
if (strcmp("post",v)==0) return(1);
if (strcmp("potential",v)==0) return(1);
if (strcmp("potential",v)==0) return(1);
if (strcmp("pound",v)==0) return(1);
if (strcmp("power",v)==0) return(1);
if (strcmp("powerful",v)==0) return(1);
if (strcmp("practical",v)==0) return(1);
if (strcmp("practice",v)==0) return(1);
if (strcmp("prefer",v)==0) return(1);
if (strcmp("prepare",v)==0) return(1);
if (strcmp("presence",v)==0) return(1);
if (strcmp("present",v)==0) return(1);
if (strcmp("present",v)==0) return(1);
if (strcmp("present",v)==0) return(1);
if (strcmp("president",v)==0) return(1);
if (strcmp("press",v)==0) return(1);
if (strcmp("press",v)==0) return(1);
if (strcmp("pressure",v)==0) return(1);
if (strcmp("pretty",v)==0) return(1);
if (strcmp("prevent",v)==0) return(1);
if (strcmp("previous",v)==0) return(1);
if (strcmp("previously",v)==0) return(1);
if (strcmp("price",v)==0) return(1);
if (strcmp("primary",v)==0) return(1);
if (strcmp("prime",v)==0) return(1);
if (strcmp("principle",v)==0) return(1);
if (strcmp("priority",v)==0) return(1);
if (strcmp("prison",v)==0) return(1);
if (strcmp("prisoner",v)==0) return(1);
if (strcmp("private",v)==0) return(1);
if (strcmp("probably",v)==0) return(1);
if (strcmp("problem",v)==0) return(1);
if (strcmp("procedure",v)==0) return(1);
if (strcmp("process",v)==0) return(1);
if (strcmp("produce",v)==0) return(1);
if (strcmp("product",v)==0) return(1);
if (strcmp("production",v)==0) return(1);
if (strcmp("professional",v)==0) return(1);
if (strcmp("profit",v)==0) return(1);
if (strcmp("program",v)==0) return(1);
if (strcmp("programme",v)==0) return(1);
if (strcmp("progress",v)==0) return(1);
if (strcmp("project",v)==0) return(1);
if (strcmp("promise",v)==0) return(1);
if (strcmp("promote",v)==0) return(1);
if (strcmp("proper",v)==0) return(1);
if (strcmp("properly",v)==0) return(1);
if (strcmp("property",v)==0) return(1);
if (strcmp("proportion",v)==0) return(1);
if (strcmp("propose",v)==0) return(1);
if (strcmp("proposal",v)==0) return(1);
if (strcmp("prospect",v)==0) return(1);
if (strcmp("protect",v)==0) return(1);
if (strcmp("protection",v)==0) return(1);
if (strcmp("prove",v)==0) return(1);
if (strcmp("provide",v)==0) return(1);
if (strcmp("provided",v)==0) return(1);
if (strcmp("provision",v)==0) return(1);
if (strcmp("pub",v)==0) return(1);
if (strcmp("public",v)==0) return(1);
if (strcmp("public",v)==0) return(1);
if (strcmp("publication",v)==0) return(1);
if (strcmp("publish",v)==0) return(1);
if (strcmp("pull",v)==0) return(1);
if (strcmp("pupil",v)==0) return(1);
if (strcmp("purpose",v)==0) return(1);
if (strcmp("push",v)==0) return(1);
if (strcmp("put",v)==0) return(1);
if (strcmp("quality",v)==0) return(1);
if (strcmp("quarter",v)==0) return(1);
if (strcmp("question",v)==0) return(1);
if (strcmp("question",v)==0) return(1);
if (strcmp("quick",v)==0) return(1);
if (strcmp("quickly",v)==0) return(1);
if (strcmp("quiet",v)==0) return(1);
if (strcmp("quite",v)==0) return(1);
if (strcmp("race",v)==0) return(1);
if (strcmp("radio",v)==0) return(1);
if (strcmp("railway",v)==0) return(1);
if (strcmp("rain",v)==0) return(1);
if (strcmp("raise",v)==0) return(1);
if (strcmp("range",v)==0) return(1);
if (strcmp("rapidly",v)==0) return(1);
if (strcmp("rare",v)==0) return(1);
if (strcmp("rate",v)==0) return(1);
if (strcmp("rather",v)==0) return(1);
if (strcmp("reach",v)==0) return(1);
if (strcmp("reaction",v)==0) return(1);
if (strcmp("read",v)==0) return(1);
if (strcmp("reader",v)==0) return(1);
if (strcmp("reading",v)==0) return(1);
if (strcmp("ready",v)==0) return(1);
if (strcmp("real",v)==0) return(1);
if (strcmp("realise",v)==0) return(1);
if (strcmp("reality",v)==0) return(1);
if (strcmp("realize",v)==0) return(1);
if (strcmp("really",v)==0) return(1);
if (strcmp("reason",v)==0) return(1);
if (strcmp("reasonable",v)==0) return(1);
if (strcmp("recall",v)==0) return(1);
if (strcmp("receive",v)==0) return(1);
if (strcmp("recent",v)==0) return(1);
if (strcmp("recently",v)==0) return(1);
if (strcmp("recognise",v)==0) return(1);
if (strcmp("recognition",v)==0) return(1);
if (strcmp("recognize",v)==0) return(1);
if (strcmp("recommend",v)==0) return(1);
if (strcmp("record",v)==0) return(1);
if (strcmp("record",v)==0) return(1);
if (strcmp("recover",v)==0) return(1);
if (strcmp("red",v)==0) return(1);
if (strcmp("reduce",v)==0) return(1);
if (strcmp("reduction",v)==0) return(1);
if (strcmp("refer",v)==0) return(1);
if (strcmp("reference",v)==0) return(1);
if (strcmp("reflect",v)==0) return(1);
if (strcmp("reform",v)==0) return(1);
if (strcmp("refuse",v)==0) return(1);
if (strcmp("regard",v)==0) return(1);
if (strcmp("region",v)==0) return(1);
if (strcmp("regional",v)==0) return(1);
if (strcmp("regular",v)==0) return(1);
if (strcmp("regulation",v)==0) return(1);
if (strcmp("reject",v)==0) return(1);
if (strcmp("relate",v)==0) return(1);
if (strcmp("relation",v)==0) return(1);
if (strcmp("relationship",v)==0) return(1);
if (strcmp("relative",v)==0) return(1);
if (strcmp("relatively",v)==0) return(1);
if (strcmp("release",v)==0) return(1);
if (strcmp("release",v)==0) return(1);
if (strcmp("relevant",v)==0) return(1);
if (strcmp("relief",v)==0) return(1);
if (strcmp("religion",v)==0) return(1);
if (strcmp("religious",v)==0) return(1);
if (strcmp("rely",v)==0) return(1);
if (strcmp("remain",v)==0) return(1);
if (strcmp("remember",v)==0) return(1);
if (strcmp("remind",v)==0) return(1);
if (strcmp("remove",v)==0) return(1);
if (strcmp("repeat",v)==0) return(1);
if (strcmp("replace",v)==0) return(1);
if (strcmp("reply",v)==0) return(1);
if (strcmp("report",v)==0) return(1);
if (strcmp("report",v)==0) return(1);
if (strcmp("represent",v)==0) return(1);
if (strcmp("representation",v)==0) return(1);
if (strcmp("representative",v)==0) return(1);
if (strcmp("request",v)==0) return(1);
if (strcmp("require",v)==0) return(1);
if (strcmp("requirement",v)==0) return(1);
if (strcmp("research",v)==0) return(1);
if (strcmp("resource",v)==0) return(1);
if (strcmp("respect",v)==0) return(1);
if (strcmp("respond",v)==0) return(1);
if (strcmp("response",v)==0) return(1);
if (strcmp("responsibility",v)==0) return(1);
if (strcmp("responsible",v)==0) return(1);
if (strcmp("rest",v)==0) return(1);
if (strcmp("rest",v)==0) return(1);
if (strcmp("restaurant",v)==0) return(1);
if (strcmp("result",v)==0) return(1);
if (strcmp("result",v)==0) return(1);
if (strcmp("retain",v)==0) return(1);
if (strcmp("return",v)==0) return(1);
if (strcmp("return",v)==0) return(1);
if (strcmp("reveal",v)==0) return(1);
if (strcmp("revenue",v)==0) return(1);
if (strcmp("review",v)==0) return(1);
if (strcmp("revolution",v)==0) return(1);
if (strcmp("rich",v)==0) return(1);
if (strcmp("ride",v)==0) return(1);
if (strcmp("right",v)==0) return(1);
if (strcmp("right",v)==0) return(1);
if (strcmp("right",v)==0) return(1);
if (strcmp("ring",v)==0) return(1);
if (strcmp("ring",v)==0) return(1);
if (strcmp("rise",v)==0) return(1);
if (strcmp("rise",v)==0) return(1);
if (strcmp("risk",v)==0) return(1);
if (strcmp("river",v)==0) return(1);
if (strcmp("road",v)==0) return(1);
if (strcmp("rock",v)==0) return(1);
if (strcmp("role",v)==0) return(1);
if (strcmp("roll",v)==0) return(1);
if (strcmp("roof",v)==0) return(1);
if (strcmp("room",v)==0) return(1);
if (strcmp("round",v)==0) return(1);
if (strcmp("round",v)==0) return(1);
if (strcmp("route",v)==0) return(1);
if (strcmp("row",v)==0) return(1);
if (strcmp("royal",v)==0) return(1);
if (strcmp("rule",v)==0) return(1);
if (strcmp("run",v)==0) return(1);
if (strcmp("run",v)==0) return(1);
if (strcmp("rural",v)==0) return(1);
if (strcmp("safe",v)==0) return(1);
if (strcmp("safety",v)==0) return(1);
if (strcmp("sale",v)==0) return(1);
if (strcmp("same",v)==0) return(1);
if (strcmp("sample",v)==0) return(1);
if (strcmp("satisfy",v)==0) return(1);
if (strcmp("save",v)==0) return(1);
if (strcmp("say",v)==0) return(1);
if (strcmp("scale",v)==0) return(1);
if (strcmp("scene",v)==0) return(1);
if (strcmp("scheme",v)==0) return(1);
if (strcmp("school",v)==0) return(1);
if (strcmp("science",v)==0) return(1);
if (strcmp("scientific",v)==0) return(1);
if (strcmp("scientist",v)==0) return(1);
if (strcmp("score",v)==0) return(1);
if (strcmp("screen",v)==0) return(1);
if (strcmp("sea",v)==0) return(1);
if (strcmp("search",v)==0) return(1);
if (strcmp("search",v)==0) return(1);
if (strcmp("season",v)==0) return(1);
if (strcmp("seat",v)==0) return(1);
if (strcmp("second",v)==0) return(1);
if (strcmp("secondary",v)==0) return(1);
if (strcmp("secretary",v)==0) return(1);
if (strcmp("section",v)==0) return(1);
if (strcmp("sector",v)==0) return(1);
if (strcmp("secure",v)==0) return(1);
if (strcmp("security",v)==0) return(1);
if (strcmp("see",v)==0) return(1);
if (strcmp("seek",v)==0) return(1);
if (strcmp("seem",v)==0) return(1);
if (strcmp("select",v)==0) return(1);
if (strcmp("selection",v)==0) return(1);
if (strcmp("sell",v)==0) return(1);
if (strcmp("send",v)==0) return(1);
if (strcmp("senior",v)==0) return(1);
if (strcmp("sense",v)==0) return(1);
if (strcmp("sentence",v)==0) return(1);
if (strcmp("separate",v)==0) return(1);
if (strcmp("separate",v)==0) return(1);
if (strcmp("sequence",v)==0) return(1);
if (strcmp("series",v)==0) return(1);
if (strcmp("serious",v)==0) return(1);
if (strcmp("seriously",v)==0) return(1);
if (strcmp("servant",v)==0) return(1);
if (strcmp("serve",v)==0) return(1);
if (strcmp("service",v)==0) return(1);
if (strcmp("session",v)==0) return(1);
if (strcmp("set",v)==0) return(1);
if (strcmp("set",v)==0) return(1);
if (strcmp("settle",v)==0) return(1);
if (strcmp("settlement",v)==0) return(1);
if (strcmp("several",v)==0) return(1);
if (strcmp("severe",v)==0) return(1);
if (strcmp("sex",v)==0) return(1);
if (strcmp("sexual",v)==0) return(1);
if (strcmp("shake",v)==0) return(1);
if (strcmp("shall",v)==0) return(1);
if (strcmp("shape",v)==0) return(1);
if (strcmp("share",v)==0) return(1);
if (strcmp("share",v)==0) return(1);
if (strcmp("she",v)==0) return(1);
if (strcmp("sheet",v)==0) return(1);
if (strcmp("ship",v)==0) return(1);
if (strcmp("shoe",v)==0) return(1);
if (strcmp("shoot",v)==0) return(1);
if (strcmp("shop",v)==0) return(1);
if (strcmp("short",v)==0) return(1);
if (strcmp("shot",v)==0) return(1);
if (strcmp("should",v)==0) return(1);
if (strcmp("shoulder",v)==0) return(1);
if (strcmp("shout",v)==0) return(1);
if (strcmp("show",v)==0) return(1);
if (strcmp("show",v)==0) return(1);
if (strcmp("shut",v)==0) return(1);
if (strcmp("side",v)==0) return(1);
if (strcmp("sight",v)==0) return(1);
if (strcmp("sign",v)==0) return(1);
if (strcmp("sign",v)==0) return(1);
if (strcmp("signal",v)==0) return(1);
if (strcmp("significance",v)==0) return(1);
if (strcmp("significant",v)==0) return(1);
if (strcmp("silence",v)==0) return(1);
if (strcmp("similar",v)==0) return(1);
if (strcmp("simple",v)==0) return(1);
if (strcmp("simply",v)==0) return(1);
if (strcmp("since",v)==0) return(1);
if (strcmp("since",v)==0) return(1);
if (strcmp("sing",v)==0) return(1);
if (strcmp("single",v)==0) return(1);
if (strcmp("sir",v)==0) return(1);
if (strcmp("sister",v)==0) return(1);
if (strcmp("sit",v)==0) return(1);
if (strcmp("site",v)==0) return(1);
if (strcmp("situation",v)==0) return(1);
if (strcmp("size",v)==0) return(1);
if (strcmp("skill",v)==0) return(1);
if (strcmp("skin",v)==0) return(1);
if (strcmp("sky",v)==0) return(1);
if (strcmp("sleep",v)==0) return(1);
if (strcmp("slightly",v)==0) return(1);
if (strcmp("slip",v)==0) return(1);
if (strcmp("slow",v)==0) return(1);
if (strcmp("slowly",v)==0) return(1);
if (strcmp("small",v)==0) return(1);
if (strcmp("smile",v)==0) return(1);
if (strcmp("smile",v)==0) return(1);
if (strcmp("so",v)==0) return(1);
if (strcmp("so",v)==0) return(1);
if (strcmp("social",v)==0) return(1);
if (strcmp("society",v)==0) return(1);
if (strcmp("soft",v)==0) return(1);
if (strcmp("software",v)==0) return(1);
if (strcmp("soil",v)==0) return(1);
if (strcmp("soldier",v)==0) return(1);
if (strcmp("solicitor",v)==0) return(1);
if (strcmp("solution",v)==0) return(1);
if (strcmp("some",v)==0) return(1);
if (strcmp("somebody",v)==0) return(1);
if (strcmp("someone",v)==0) return(1);
if (strcmp("something",v)==0) return(1);
if (strcmp("sometimes",v)==0) return(1);
if (strcmp("somewhat",v)==0) return(1);
if (strcmp("somewhere",v)==0) return(1);
if (strcmp("son",v)==0) return(1);
if (strcmp("song",v)==0) return(1);
if (strcmp("soon",v)==0) return(1);
if (strcmp("sorry",v)==0) return(1);
if (strcmp("sort",v)==0) return(1);
if (strcmp("sound",v)==0) return(1);
if (strcmp("sound",v)==0) return(1);
if (strcmp("source",v)==0) return(1);
if (strcmp("south",v)==0) return(1);
if (strcmp("southern",v)==0) return(1);
if (strcmp("space",v)==0) return(1);
if (strcmp("speak",v)==0) return(1);
if (strcmp("speaker",v)==0) return(1);
if (strcmp("special",v)==0) return(1);
if (strcmp("species",v)==0) return(1);
if (strcmp("specific",v)==0) return(1);
if (strcmp("speech",v)==0) return(1);
if (strcmp("speed",v)==0) return(1);
if (strcmp("spend",v)==0) return(1);
if (strcmp("spirit",v)==0) return(1);
if (strcmp("sport",v)==0) return(1);
if (strcmp("spot",v)==0) return(1);
if (strcmp("spread",v)==0) return(1);
if (strcmp("spring",v)==0) return(1);
if (strcmp("staff",v)==0) return(1);
if (strcmp("stage",v)==0) return(1);
if (strcmp("stand",v)==0) return(1);
if (strcmp("standard",v)==0) return(1);
if (strcmp("standard",v)==0) return(1);
if (strcmp("star",v)==0) return(1);
if (strcmp("star",v)==0) return(1);
if (strcmp("start",v)==0) return(1);
if (strcmp("start",v)==0) return(1);
if (strcmp("state",v)==0) return(1);
if (strcmp("state",v)==0) return(1);
if (strcmp("statement",v)==0) return(1);
if (strcmp("station",v)==0) return(1);
if (strcmp("status",v)==0) return(1);
if (strcmp("stay",v)==0) return(1);
if (strcmp("steal",v)==0) return(1);
if (strcmp("step",v)==0) return(1);
if (strcmp("step",v)==0) return(1);
if (strcmp("stick",v)==0) return(1);
if (strcmp("still",v)==0) return(1);
if (strcmp("stock",v)==0) return(1);
if (strcmp("stone",v)==0) return(1);
if (strcmp("stop",v)==0) return(1);
if (strcmp("store",v)==0) return(1);
if (strcmp("story",v)==0) return(1);
if (strcmp("straight",v)==0) return(1);
if (strcmp("strange",v)==0) return(1);
if (strcmp("strategy",v)==0) return(1);
if (strcmp("street",v)==0) return(1);
if (strcmp("strength",v)==0) return(1);
if (strcmp("strike",v)==0) return(1);
if (strcmp("strike",v)==0) return(1);
if (strcmp("strong",v)==0) return(1);
if (strcmp("strongly",v)==0) return(1);
if (strcmp("structure",v)==0) return(1);
if (strcmp("student",v)==0) return(1);
if (strcmp("studio",v)==0) return(1);
if (strcmp("study",v)==0) return(1);
if (strcmp("study",v)==0) return(1);
if (strcmp("stuff",v)==0) return(1);
if (strcmp("style",v)==0) return(1);
if (strcmp("subject",v)==0) return(1);
if (strcmp("substantial",v)==0) return(1);
if (strcmp("succeed",v)==0) return(1);
if (strcmp("success",v)==0) return(1);
if (strcmp("successful",v)==0) return(1);
if (strcmp("such",v)==0) return(1);
if (strcmp("suddenly",v)==0) return(1);
if (strcmp("suffer",v)==0) return(1);
if (strcmp("sufficient",v)==0) return(1);
if (strcmp("suggest",v)==0) return(1);
if (strcmp("suggestion",v)==0) return(1);
if (strcmp("suitable",v)==0) return(1);
if (strcmp("sum",v)==0) return(1);
if (strcmp("summer",v)==0) return(1);
if (strcmp("sun",v)==0) return(1);
if (strcmp("supply",v)==0) return(1);
if (strcmp("supply",v)==0) return(1);
if (strcmp("support",v)==0) return(1);
if (strcmp("support",v)==0) return(1);
if (strcmp("suppose",v)==0) return(1);
if (strcmp("sure",v)==0) return(1);
if (strcmp("surely",v)==0) return(1);
if (strcmp("surface",v)==0) return(1);
if (strcmp("surprise",v)==0) return(1);
if (strcmp("surround",v)==0) return(1);
if (strcmp("survey",v)==0) return(1);
if (strcmp("survive",v)==0) return(1);
if (strcmp("switch",v)==0) return(1);
if (strcmp("system",v)==0) return(1);
if (strcmp("table",v)==0) return(1);
if (strcmp("take",v)==0) return(1);
if (strcmp("talk",v)==0) return(1);
if (strcmp("talk",v)==0) return(1);
if (strcmp("tall",v)==0) return(1);
if (strcmp("tape",v)==0) return(1);
if (strcmp("target",v)==0) return(1);
if (strcmp("task",v)==0) return(1);
if (strcmp("tax",v)==0) return(1);
if (strcmp("tea",v)==0) return(1);
if (strcmp("teach",v)==0) return(1);
if (strcmp("teacher",v)==0) return(1);
if (strcmp("teaching",v)==0) return(1);
if (strcmp("team",v)==0) return(1);
if (strcmp("tear",v)==0) return(1);
if (strcmp("technical",v)==0) return(1);
if (strcmp("technique",v)==0) return(1);
if (strcmp("technology",v)==0) return(1);
if (strcmp("telephone",v)==0) return(1);
if (strcmp("television",v)==0) return(1);
if (strcmp("tell",v)==0) return(1);
if (strcmp("temperature",v)==0) return(1);
if (strcmp("tend",v)==0) return(1);
if (strcmp("term",v)==0) return(1);
if (strcmp("terms",v)==0) return(1);
if (strcmp("terrible",v)==0) return(1);
if (strcmp("test",v)==0) return(1);
if (strcmp("test",v)==0) return(1);
if (strcmp("text",v)==0) return(1);
if (strcmp("than",v)==0) return(1);
if (strcmp("thank",v)==0) return(1);
if (strcmp("thanks",v)==0) return(1);
if (strcmp("that",v)==0) return(1);
if (strcmp("that",v)==0) return(1);
if (strcmp("the",v)==0) return(1);
if (strcmp("theatre",v)==0) return(1);
if (strcmp("their",v)==0) return(1);
if (strcmp("them",v)==0) return(1);
if (strcmp("theme",v)==0) return(1);
if (strcmp("themselves",v)==0) return(1);
if (strcmp("then",v)==0) return(1);
if (strcmp("theory",v)==0) return(1);
if (strcmp("there",v)==0) return(1);
if (strcmp("there",v)==0) return(1);
if (strcmp("therefore",v)==0) return(1);
if (strcmp("these",v)==0) return(1);
if (strcmp("they",v)==0) return(1);
if (strcmp("thin",v)==0) return(1);
if (strcmp("thing",v)==0) return(1);
if (strcmp("think",v)==0) return(1);
if (strcmp("this",v)==0) return(1);
if (strcmp("those",v)==0) return(1);
if (strcmp("though",v)==0) return(1);
if (strcmp("though",v)==0) return(1);
if (strcmp("thought",v)==0) return(1);
if (strcmp("threat",v)==0) return(1);
if (strcmp("threaten",v)==0) return(1);
if (strcmp("through",v)==0) return(1);
if (strcmp("through",v)==0) return(1);
if (strcmp("throughout",v)==0) return(1);
if (strcmp("throw",v)==0) return(1);
if (strcmp("thus",v)==0) return(1);
if (strcmp("ticket",v)==0) return(1);
if (strcmp("time",v)==0) return(1);
if (strcmp("tiny",v)==0) return(1);
if (strcmp("title",v)==0) return(1);
if (strcmp("to",v)==0) return(1);
if (strcmp("to",v)==0) return(1);
if (strcmp("to",v)==0) return(1);
if (strcmp("today",v)==0) return(1);
if (strcmp("together",v)==0) return(1);
if (strcmp("tomorrow",v)==0) return(1);
if (strcmp("tone",v)==0) return(1);
if (strcmp("tonight",v)==0) return(1);
if (strcmp("too",v)==0) return(1);
if (strcmp("tool",v)==0) return(1);
if (strcmp("tooth",v)==0) return(1);
if (strcmp("top",v)==0) return(1);
if (strcmp("top",v)==0) return(1);
if (strcmp("total",v)==0) return(1);
if (strcmp("total",v)==0) return(1);
if (strcmp("totally",v)==0) return(1);
if (strcmp("touch",v)==0) return(1);
if (strcmp("touch",v)==0) return(1);
if (strcmp("tour",v)==0) return(1);
if (strcmp("towards",v)==0) return(1);
if (strcmp("town",v)==0) return(1);
if (strcmp("track",v)==0) return(1);
if (strcmp("trade",v)==0) return(1);
if (strcmp("tradition",v)==0) return(1);
if (strcmp("traditional",v)==0) return(1);
if (strcmp("traffic",v)==0) return(1);
if (strcmp("train",v)==0) return(1);
if (strcmp("train",v)==0) return(1);
if (strcmp("training",v)==0) return(1);
if (strcmp("transfer",v)==0) return(1);
if (strcmp("transfer",v)==0) return(1);
if (strcmp("transport",v)==0) return(1);
if (strcmp("travel",v)==0) return(1);
if (strcmp("treat",v)==0) return(1);
if (strcmp("treatment",v)==0) return(1);
if (strcmp("treaty",v)==0) return(1);
if (strcmp("tree",v)==0) return(1);
if (strcmp("trend",v)==0) return(1);
if (strcmp("trial",v)==0) return(1);
if (strcmp("trip",v)==0) return(1);
if (strcmp("troop",v)==0) return(1);
if (strcmp("trouble",v)==0) return(1);
if (strcmp("true",v)==0) return(1);
if (strcmp("trust",v)==0) return(1);
if (strcmp("truth",v)==0) return(1);
if (strcmp("try",v)==0) return(1);
if (strcmp("turn",v)==0) return(1);
if (strcmp("turn",v)==0) return(1);
if (strcmp("twice",v)==0) return(1);
if (strcmp("type",v)==0) return(1);
if (strcmp("typical",v)==0) return(1);
if (strcmp("unable",v)==0) return(1);
if (strcmp("under",v)==0) return(1);
if (strcmp("under",v)==0) return(1);
if (strcmp("understand",v)==0) return(1);
if (strcmp("understanding",v)==0) return(1);
if (strcmp("undertake",v)==0) return(1);
if (strcmp("unemployment",v)==0) return(1);
if (strcmp("unfortunately",v)==0) return(1);
if (strcmp("union",v)==0) return(1);
if (strcmp("unit",v)==0) return(1);
if (strcmp("united",v)==0) return(1);
if (strcmp("university",v)==0) return(1);
if (strcmp("unless",v)==0) return(1);
if (strcmp("unlikely",v)==0) return(1);
if (strcmp("until",v)==0) return(1);
if (strcmp("until",v)==0) return(1);
if (strcmp("up",v)==0) return(1);
if (strcmp("up",v)==0) return(1);
if (strcmp("upon",v)==0) return(1);
if (strcmp("upper",v)==0) return(1);
if (strcmp("urban",v)==0) return(1);
if (strcmp("us",v)==0) return(1);
if (strcmp("use",v)==0) return(1);
if (strcmp("use",v)==0) return(1);
if (strcmp("used",v)==0) return(1);
if (strcmp("used",v)==0) return(1);
if (strcmp("useful",v)==0) return(1);
if (strcmp("user",v)==0) return(1);
if (strcmp("usual",v)==0) return(1);
if (strcmp("usually",v)==0) return(1);
if (strcmp("value",v)==0) return(1);
if (strcmp("variation",v)==0) return(1);
if (strcmp("variety",v)==0) return(1);
if (strcmp("various",v)==0) return(1);
if (strcmp("vary",v)==0) return(1);
if (strcmp("vast",v)==0) return(1);
if (strcmp("vehicle",v)==0) return(1);
if (strcmp("version",v)==0) return(1);
if (strcmp("very",v)==0) return(1);
if (strcmp("very",v)==0) return(1);
if (strcmp("via",v)==0) return(1);
if (strcmp("victim",v)==0) return(1);
if (strcmp("victory",v)==0) return(1);
if (strcmp("video",v)==0) return(1);
if (strcmp("view",v)==0) return(1);
if (strcmp("village",v)==0) return(1);
if (strcmp("violence",v)==0) return(1);
if (strcmp("vision",v)==0) return(1);
if (strcmp("visit",v)==0) return(1);
if (strcmp("visit",v)==0) return(1);
if (strcmp("visitor",v)==0) return(1);
if (strcmp("vital",v)==0) return(1);
if (strcmp("voice",v)==0) return(1);
if (strcmp("volume",v)==0) return(1);
if (strcmp("vote",v)==0) return(1);
if (strcmp("vote",v)==0) return(1);
if (strcmp("wage",v)==0) return(1);
if (strcmp("wait",v)==0) return(1);
if (strcmp("walk",v)==0) return(1);
if (strcmp("walk",v)==0) return(1);
if (strcmp("wall",v)==0) return(1);
if (strcmp("want",v)==0) return(1);
if (strcmp("war",v)==0) return(1);
if (strcmp("warm",v)==0) return(1);
if (strcmp("warn",v)==0) return(1);
if (strcmp("was",v)==0) return(1);
if (strcmp("wasn",v)==0) return(1);
if (strcmp("wash",v)==0) return(1);
if (strcmp("watch",v)==0) return(1);
if (strcmp("water",v)==0) return(1);
if (strcmp("wave",v)==0) return(1);
if (strcmp("way",v)==0) return(1);
if (strcmp("we",v)==0) return(1);
if (strcmp("weak",v)==0) return(1);
if (strcmp("weapon",v)==0) return(1);
if (strcmp("wear",v)==0) return(1);
if (strcmp("weather",v)==0) return(1);
if (strcmp("week",v)==0) return(1);
if (strcmp("weekend",v)==0) return(1);
if (strcmp("weight",v)==0) return(1);
if (strcmp("welcome",v)==0) return(1);
if (strcmp("welfare",v)==0) return(1);
if (strcmp("well",v)==0) return(1);
if (strcmp("well",v)==0) return(1);
if (strcmp("west",v)==0) return(1);
if (strcmp("western",v)==0) return(1);
if (strcmp("what",v)==0) return(1);
if (strcmp("whatever",v)==0) return(1);
if (strcmp("when",v)==0) return(1);
if (strcmp("when",v)==0) return(1);
if (strcmp("where",v)==0) return(1);
if (strcmp("where",v)==0) return(1);
if (strcmp("whereas",v)==0) return(1);
if (strcmp("whether",v)==0) return(1);
if (strcmp("which",v)==0) return(1);
if (strcmp("while",v)==0) return(1);
if (strcmp("while",v)==0) return(1);
if (strcmp("whilst",v)==0) return(1);
if (strcmp("white",v)==0) return(1);
if (strcmp("who",v)==0) return(1);
if (strcmp("whole",v)==0) return(1);
if (strcmp("whole",v)==0) return(1);
if (strcmp("whom",v)==0) return(1);
if (strcmp("whose",v)==0) return(1);
if (strcmp("why",v)==0) return(1);
if (strcmp("wide",v)==0) return(1);
if (strcmp("widely",v)==0) return(1);
if (strcmp("wife",v)==0) return(1);
if (strcmp("wild",v)==0) return(1);
if (strcmp("will",v)==0) return(1);
if (strcmp("will",v)==0) return(1);
if (strcmp("win",v)==0) return(1);
if (strcmp("wind",v)==0) return(1);
if (strcmp("window",v)==0) return(1);
if (strcmp("wine",v)==0) return(1);
if (strcmp("wing",v)==0) return(1);
if (strcmp("winner",v)==0) return(1);
if (strcmp("winter",v)==0) return(1);
if (strcmp("wish",v)==0) return(1);
if (strcmp("with",v)==0) return(1);
if (strcmp("withdraw",v)==0) return(1);
if (strcmp("within",v)==0) return(1);
if (strcmp("without",v)==0) return(1);
if (strcmp("woman",v)==0) return(1);
if (strcmp("wonder",v)==0) return(1);
if (strcmp("wonderful",v)==0) return(1);
if (strcmp("wood",v)==0) return(1);
if (strcmp("word",v)==0) return(1);
if (strcmp("work",v)==0) return(1);
if (strcmp("work",v)==0) return(1);
if (strcmp("worker",v)==0) return(1);
if (strcmp("working",v)==0) return(1);
if (strcmp("works",v)==0) return(1);
if (strcmp("world",v)==0) return(1);
if (strcmp("worry",v)==0) return(1);
if (strcmp("worth",v)==0) return(1);
if (strcmp("would",v)==0) return(1);
if (strcmp("write",v)==0) return(1);
if (strcmp("writer",v)==0) return(1);
if (strcmp("writing",v)==0) return(1);
if (strcmp("wrong",v)==0) return(1);
if (strcmp("yard",v)==0) return(1);
if (strcmp("yeah",v)==0) return(1);
if (strcmp("year",v)==0) return(1);
if (strcmp("yes",v)==0) return(1);
if (strcmp("yesterday",v)==0) return(1);
if (strcmp("yet",v)==0) return(1);
if (strcmp("you",v)==0) return(1);
if (strcmp("young",v)==0) return(1);
if (strcmp("your",v)==0) return(1);
if (strcmp("yourself",v)==0) return(1);
if (strcmp("youth",v)==0) return(1);
	return(0);
}

int
fuzzed(void)
{
	return(gn);
}

void
dolog(const char *v) {
	openlog("pmess",LOG_PID,1);
	syslog(LOG_INFO,v);
	closelog();
}

char *
strtolower(char *src)
{
	for (int i=0;i<strlen(src);i++) {
		src[i] = tolower(src[i]);
	}
	return (src);
}

char *
alpha(char *src)
{
        for (int i=0;i<strlen(src);i++) {
		if (isalpha(src[i])) {
                	src[i] = tolower(src[i]);
		} else {
			src[i] = ' ';
		}
        }
        return (src);
}


void 
rf(char *f,long fstart, long fend, long end_body) {

	const char *tz="-0000-0100-0200-0300-0400-0500-0600-0700-0800-0900-1000-1100-1200+0000+0100+0200+0300+0400+0500+0600+0700+0800+0900+1000+1100+1200+1300+1400+0330+0430+0530+0630+0930+1030+1130-0330-0430-0930+1245+0545";

	mongo conn;

        //connect to mongodb on local. if no connect, bail
        if( mongo_client( &conn, "127.0.0.1", 27017 ) != MONGO_OK ) {
                switch( conn.err ) {
                        case MONGO_CONN_NO_SOCKET:
                                dolog("FAIL: No Connecto Socket.");
                                break; 
                        case MONGO_CONN_FAIL:
                                dolog("FAIL: No Connecto.\n");
                                break;
                }
                exit( 1 );
        }


	
	char hostname[_POSIX_HOST_NAME_MAX] = {0};

	gethostname(hostname,_POSIX_HOST_NAME_MAX);

	FILE *file = fopen(f,"r");
	
	char *buffer;
	char *loc;
	long lSize;
	size_t result;
	lSize = fend-fstart;
	char bd[71]={0};
	char contentType[255]={0};
	char charset[32]={0};
	int has_charset=0;
	int has_boundary=0;

	fseek(file,fstart,SEEK_SET);
	buffer = (char*) malloc (sizeof(char)*lSize*2);
	result = fread(buffer,1,lSize,file);

	//unfold lines in header
	int j;
	for (j=0;j<strlen(buffer)-1;j++) {
		if (buffer[j]=='\n') {
			if ((buffer[j+1]==' ')||(buffer[j+1]=='\t')) {
				buffer[j]=' ';
				j++;
			}
		}
	}

	//replace tabs with spaces
	int len;
	len = strlen(buffer);
	for (j=0;j<len;j++) {
		if (buffer[j]=='\t') {
			buffer[j]=' ';
		}
	}

	//strip extra whitespace
	while (strstr(buffer,"  ")) {
		for (j=0;j<len-1;j++) {
			if (buffer[j]==' ') {
				if (buffer[j+1]==' ') {
					memmove(&buffer[j],&buffer[j+1],
						(len-j-1));
					//printf("%i\n",len);
					len--;
					buffer[len]='\0';
				}
			}
		}
	}

	int start = 0;
	int prong = 0;
	int reset = 0;
	bson b;

	uuid_t *store;
	char *up;
	store = (uuid_t*)malloc(sizeof(uuid_t));
	uuidgen(store,1);
	uuid_to_string(store, &up, NULL);

	char outstr[200] = {0};
	time_t t;
	struct tm *tmp;
	t = time(NULL);
	tmp = localtime(&t);
	strftime(outstr, sizeof(outstr), "%a, %d %b %Y %T %z", tmp);

	bson_init(&b);

	bson_set_oid_fuzz(fuzzed);
	bson_append_new_oid(&b,"_id");
	bson_append_string(&b,"UUID",up);
	bson_append_start_object(&b,"origin");
	bson_append_string(&b,"hostname",hostname);
	bson_append_string(&b,"initdate",outstr);
	bson_append_finish_object(&b);

	bson_append_start_object(&b,"greenroom");
	bson_append_string(&b,"hostname","-");
	bson_append_int(&b,"processed",0);
	bson_append_int(&b,"seen",0);
	bson_append_int(&b,"flagged",0);
	bson_append_int(&b,"slide",0);
	bson_append_finish_object(&b);

	bson_append_start_object(&b,"headers");
	int tt=0;

	for (j=0;j<len;j++) {
		if (reset==0) {
			if (buffer[j]==':') {
				prong=j;
				reset=1;
			}
		}
		//split the header line at the first ':'
		if (buffer[j]=='\n') {

			char d[80] = {0};
 			char r[8192] = {0};

			memcpy(&d,&buffer[start],prong-start);
			d[prong-start]='\0';
			memcpy(&r,&buffer[prong+1],j-prong-1);
			r[j-prong-1]='\0';
			//remove leading space if exists
			if (r[0]==' ') {
				memmove(&r[0],&r[1],j-prong-2);
				r[j-prong-2]='\0';
			}
			//remove $,. from d
			for (int k=0;k<strlen(d);k++) {
				if (d[k]=='$') d[k]='_';
				if (d[j]=='.') d[k]='_';
			}
			reset=0;
			start=j+1;

			char ndate[26]={0};
			int dondate=0;

			//attempt to find timezone in line to parse date
			for (int k=0;k<strlen(tz);k+=5) {
				if (dondate<1) {
				char x[6]={0};
				memcpy(&x[0],&tz[k],5);
				x[6]='\0';
				loc = strstr(r,x);
				if (loc) {
					//solve -0000 in id
					if (r[loc-r-1]==' ') {
					int dtstart=(loc-r)-21;
					if (r[dtstart]==' ') {
						ndate[0]='0';
						memcpy(&ndate[1],&r[dtstart+1],
							25);
						ndate[26]='\0';
						dondate=1;
					} else {
						memcpy(&ndate[0],&r[dtstart],
							26);
						ndate[26]='\0';
						dondate=1;
					}
					}
				}
				}
			}

			if (dondate>0) {
				char ts[255]={0};
				sprintf(ts,"%i",tt++);
				bson_append_start_object(&b,ts);

				bson_append_string(&b,"ph",ndate);
				bson_append_string(&b,d,r);
				bson_append_finish_object(&b);
			} else {
				char ts[255]={0};
				sprintf(ts,"%i",tt++);
				bson_append_start_object(&b,ts);
				bson_append_string(&b,d,r);
				bson_append_finish_object(&b);
			}

			if (!strcmp("content-type",strtolower(d))) {
				memcpy(&contentType,&r,strlen(r));
				contentType[strlen(r)]='\0';
				char *boundary = strstr(r,"boundary=");
				if (boundary) {
					int st = boundary-r+9;
					int en = strlen(r);
					if (r[st+1]=='"') st++;
					for (int ci=st;ci<strlen(r);ci++) {
						if ((r[ci]=='"')||
							(r[ci]==' ')||
							(r[ci]==';')) {
								en=ci;
								break;
						}
					}
					memcpy(&bd,&r[st],en-st);
					bd[en-st+1]='\0';
					has_boundary=1;
				}
                                char *cs = strstr(r,"charset=");
                                if (cs) {
                                        int st = cs-r+8;
                                        int en = strlen(r);
                                        if (r[st+1]=='"') st++;
                                        for (int ci=st;ci<strlen(r);ci++) {
                                                if ((r[ci]=='"')||
                                                        (r[ci]==' ')||
                                                        (r[ci]==';')) {
                                                                en=ci;
                                                                break;
                                                }
                                        }
                                        memcpy(&charset,&r[st],en-st);
                                        charset[en-st+1]='\0';
                                        has_charset=1;
                                }

			}
		}
	}
	bson_append_finish_object(&b);
	lSize = end_body-fend;
	free(buffer);
        buffer = (char*) calloc (lSize*2,sizeof(char));
        result = fread(buffer,1,lSize,file);
	bson_append_start_object(&b,"body");

//if it is not ascii try to convert to ascii
//temporary! 

if (has_charset) {
char chkc[200]={0};
sprintf(chkc,"%s",strtolower(charset));

if (!strstr(chkc,"ascii")) { 
	iconv_t cd = 0;
	cd = iconv_open("US-ASCII",chkc); 
	if (cd == (iconv_t) -1) {
		//cannot convert, perhaps no codepage
		char err[512]={0};
		sprintf(err,"Error: no codepage %s",charset);
		dolog(err);
	} else {
		size_t inbytes = 4;
		size_t outbytes = 4;
        	char *ures;
		inbytes=strlen(buffer);
        	ures = (char*) calloc (lSize*6,sizeof(char));
		char* ob = ures;
		const char* ib = buffer;
		outbytes = strlen(buffer);
		iconv(cd,&ib,&inbytes,&ob,&outbytes);
		bson_append_string(&b,"0",ures);
		free(ures);
	}
} else {
	//try it anyway, might fail
	bson_append_string(&b,"0",buffer);
}
} else {
	//no charset specified
        bson_append_string(&b,"0",buffer);
}
	bson_append_finish_object(&b);


//keywords - THINK about images/attachments
//strip non-alpha -- THINK about hyphenated words.
char *clean;
clean = (char*) calloc (lSize*2,sizeof(char));
sprintf(clean,"%s",alpha(buffer));
        //strip extra whitespace
        while (strstr(clean,"  ")) {
                for (j=0;j<len-1;j++) {
                        if (clean[j]==' ') {
                                if (clean[j+1]==' ') {
                                        memmove(&clean[j],&clean[j+1],
                                                (len-j-1));
                                        len--;
                                        clean[len]='\0';
                                }
                        }
                }
        }

//remove common words
char *token={0};
bson keys;
bson_init(&keys);
bson_append_new_oid(&keys,"_id");
bson_append_string(&keys,"UUID",up);
bson_append_start_array(&keys,"keys");

token = strtok(clean," ");
int kc=0;
while (token!=NULL)
{
	if (!is_common(token)) 
	{
		char skc[10]={0};
		sprintf(skc,"%i",kc++);
		bson_append_string(&keys,skc,token);
	}
	token = strtok(NULL," ");
}
bson_append_finish_object(&keys);

if(kc>0) {
	bson_finish(&keys);
	if( mongo_insert( &conn, "mail.keysrc", &keys, NULL ) != MONGO_OK ) {
		dolog("Could not write the keys.");
	}
	
}
	bson_destroy(&keys);

	bson_finish(&b);

	if( mongo_insert( &conn, "mail.mbox", &b, NULL ) != MONGO_OK ) {
		char err[512]={0};
		sprintf(err,"FAIL: (%d) %s %s [%i %i %i] %i",conn.err,conn.errstr,conn.lasterrstr,fstart,fend,end_body,has_boundary);
		dolog(err);
		sprintf(err,"ContentType: %s",contentType);
		dolog(err);

		char ef[24] = {0};
		FILE *efp;
		int fd = -1;
		strlcpy(ef,"/var/wrecked/err.XXXXXX",sizeof ef);
		if ((fd = mkstemp(ef)) == -1 ||
			(efp = fdopen(fd,"w+")) == NULL) {
			if (fd!=-1) {
				unlink(ef);
				close(fd);
			}
		} else {
			fprintf(efp,"%s",buffer);
			sprintf(err,"CMD [%s|%i|%i|%i]",f,fstart,fend,end_body);
	
			dolog(err);
			sprintf(err,"Errors: %s",ef);
			dolog(err);
			close(fd);
		}

	}

	bson_destroy( &b );
	mongo_destroy( &conn );
	
	fclose(file);
}

int
main (int argc, char **argv)
{
        setlocale(LC_ALL,"");
        setlocale(LC_CTYPE,"en_US.US-ASCII");

	//printf("file: %s start: %s end: %s\n",argv[1],argv[2],argv[3]);
	/*
	char mess[255] = {0};
	sprintf(mess,"file: %s start: %s end: %s",argv[1],argv[2],argv[3]);
	dolog(mess);
	*/
	gn=atoi(argv[2]);
	rf (argv[1],atoi(argv[2]),atoi(argv[3]),atoi(argv[4]));
	exit(EXIT_SUCCESS);
}

